
<div class="formBox">
<h2>Currently Editing</h2>
<p><b>Item:</b> <?php echo $this->data->title;?></p>
</div>

<div class="formBox">
<h2 class="folder">View</h2>
<ul class="idTabs">
    <li><a href="#editGallery">Gallery Details</a></li>
    <li><a href="#currentImages">Current Images</a></li>
    <li><a href="#newImage">Upload New Image</a></li>
</ul>
</div>

<div class="formBox">
<h2 class="trash">Delete gallery</h2>
<p>Would you like to permanently delete this gallery and all of the images it contains?</p>
<p><a href="/mod_gallery/index/delete/id/<?php echo $this->data->id;?>" class='deleteConfirm' title='gallery'>Delete gallery</a></p>
</div>