<?php
$this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/jquery.FCKEditor.pack.js');
$this->jQuery()->onLoadCaptureStart()?>
$('.fckeditor').fck({
	path: '<?php echo $this->getBaseUrl() . "/scripts/fckeditor/" ?>',
	toolbar: 'Digitalus',
	height: 300
});
<?php $this->jQuery()->onLoadCaptureEnd();

// get all of the controls and load them into groups
$submitButton = $this->form->getElement('submit');
$this->form->removeElement('submit');
$controls = $this->form->getElements();
foreach ($controls as $control) {
    $rel = $control->getAttrib('rel');
	$group = (!empty($rel) ? $rel : 'main');
	$groups[$group][] = $control->getName();;
}
$this->form->addDisplayGroup($groups['main'], 'main', 'main items');
unset($groups['main']);

if(is_array($groups)) {
    foreach ($groups as $key => $controls) {
        $this->form->addDisplayGroup($controls, $key);
    }
}

$displayGroups = $this->form->getDisplayGroups();

$panes = '';
foreach ($displayGroups as $title => $group) {
    $id = $title . '_content';
    $title = ucwords($title) . ' Content';
    $ids[$id] = $title;
    $content = '';
    foreach ($group->getElements() as $element) {
        $content .= $element->render();
    }
    $panes .= "<fieldset id='{$id}'><legend>{$title}</legend>{$content}<br />{$submitButton}</fieldset>";
}

$this->contentPanes = $ids;
?>
<form action='<?php $this->form->getAction()?>' method='post' enctype='multipart/form-data'>
<?php 
    echo $panes;
?>
</form>