<?php if(!$this->center->id){ ?>
<p>Sorry, there was an error loading your news center</p>
<?php }else{ ?>
<div class="newsCenter">
<h2><?php echo $this->center->title;?></h2>
<?php echo $this->RenderContent('content', $this->center);?>

<?php if(count($this->items) > 0){?>
    <ul>
        <?php
        foreach ($this->items as $item){
        ?>
        <li><span class="date"><?php echo date('m.d.y',$item->publish_date);?></span> | <a href="<?php echo $this->CleanUri(true);?>/p/openItem/<?php echo $item->id;?>"><?php echo $item->title;?></a></li>
        <?php } ?>
    </ul>
<?php }else{ ?>
    <p>There are no articles in this news center</p>
<?php }} ?>

</div>

