<h2>Search Results</h2>
<?php 
if($this->searchResults){
    $count = count($this->searchResults);
?>
<p>Your search for: <em><?php echo $this->keywords;?></em> returned <?php echo $count;?> <?php echo $this->Pluralize('result', $count);?></p>
<?php 
    foreach ($this->searchResults as $item){
?>
<h3><a href="<?php echo $this->CleanUri(true);?>/p/openItem/<?php echo $item->id;?>"><?php echo $item->title;?></a></h3>
<p><?php echo $this->TruncateText($item->content, 50);?></p>
<?php }}else{ ?>
<p>Your search did not return any results.  Try another?</p>
<?php 
//render the search form
echo $this->render('./assets/searchform.phtml');
}