<?php $this->placeholder('formHeadline')->set($this->getTranslation('Update Page'));

echo $this->render('page/edit/content.phtml');?>

<fieldset id="meta">
    <legend><?php echo $this->getTranslation('Edit Meta Data');?></legend>
    <?php echo $this->render('page/edit/meta.phtml');?>
</fieldset>

<fieldset id="properties">
    <legend><?php echo $this->getTranslation('Edit Page Properties');?></legend>
    <?php echo $this->render('page/edit/properties.phtml');?>
</fieldset>

<!--
this is not going to make it in the beta version
<fieldset id="relatedContent">
    <legend><?php echo $this->getTranslation('Related Content');?></legend>
    <?php echo $this->render('page/edit/relatedContent.phtml');?>
</fieldset>

<fieldset id="attachments">
    <legend><?php echo $this->getTranslation('Attachments');?></legend>
    <?php echo $this->render('page/edit/attachments.phtml');?>
</fieldset>
 -->

<fieldset id="template">
    <legend><?php echo $this->getTranslation('Content Template');?></legend>
    <?php echo $this->render('page/edit/template.phtml');?>
</fieldset>

<fieldset id="move">
    <legend><?php echo $this->getTranslation('Move Page');?></legend>
    <?php echo $this->render('page/edit/move.phtml');?>
</fieldset>

<fieldset id="publish">
    <legend><?php echo $this->getTranslation('Publish / Archive Page');?></legend>
    <?php echo $this->render('page/edit/publish.phtml');?>
</fieldset>
