<link rel='stylesheet' type='text/css' media='screen' href='/public/styles/ThickBox.css' /> 
<link rel='stylesheet' type='text/css' media='screen' href='/public/styles/gallery.css' /> 
<script type='text/javascript' src='/public/scripts/ThickBox.js'></script> 
<?php
if($this->images){
    foreach ($this->images as $image){ ?>
        <div class='imageTile'>
            <a href="/<?php echo $image->fullPath;?>" title="<?php echo $image->caption;?>" class="thickbox" rel="gallery-<?php echo $this->gallery->id;?>">
                <span class="imageWrapper"><img src="/<?php echo $image->thumbPath;?>" alt="<?php echo $image->caption;?>" /></span>
                <span class="caption"><?php echo $this->RenderContent($image->caption);?></span>
            </a>   
        </div> 
    <?php }
}
?>