<p>The simple gallery just displays the images as tiles with thickbox popups for full sized images...</p>

<fieldset>
    <label>Select a gallery to display</label>
    <?php
    $gallery = $this->SelectGallery('param[gallery]', $this->formParams['gallery']);
    if(!empty($gallery)){
        echo $this->FormRow('Select the gallery:', $gallery);
    }else{
        echo "<p>There are no galleries to view</p>";
    }
    ?>
</fieldset>