<?php ?>
<form action="<?php echo $this->getBaseUrl() ;?>/admin/media/rename-folder" method="post">
    <dl><?php
        echo $this->formRow($this->getTranslation('New Name'), $this->formText('folder_name', $this->label));
        echo '<dt>' . $this->formHidden('filepath', $this->filepath) . '</dt>';
        echo '<dt>' . $this->formHidden('mediapath', $this->mediapath) . '</dt>';
        echo $this->formRow('&nbsp;', $this->formSubmit('renameFolder', $this->getTranslation('Rename Folder')));?>
    </dl>
</form>