<form action='<?php echo $this->getBaseUrl();?>/admin/media/<?php echo $this->action;?>' method='post' enctype='multipart/form-data' class='uploadForm'>
    <dl>
    <?php
    echo '<dt>' . $this->formHidden('filepath', $this->filepath) . '</dt>';
    echo '<dt>' . $this->formHidden('mediapath', $this->mediapath) . '</dt>';
    echo $this->FormRow($this->getTranslation('Select the files to upload'), '<input type="file" id="multi_upload" name="uploads[]" />');
    echo $this->FormRow('&nbsp;', $this->formSubmit('uploadSubmit', $this->getTranslation('Upload Files')));
    ?>
    </dl>
</form>