<ul class="idTabs">
    <li><a href="#general"><?php echo $this->GetTranslation('Account');?></a></li>
    <li><a href="#password"><?php echo $this->GetTranslation('Credentials');?></a></li>
    <li><a href="#permissions"><?php echo $this->GetTranslation('Permissions');?></a></li>
</ul>

<h3><?php echo $this->GetTranslation('Copy User Permissions');?></h3>
<p><?php echo $this->GetTranslation("If you have another user who already has the same permissions as this user you can copy that user's role.");?></p>

<form action='/admin/user/copy-acl' method="POST">
    <?php echo $this->formHidden('id',$this->user->id);?>
    <?php echo $this->SelectUser('user_id', null, null, $this->user->id);?>
    <?php echo $this->FormSubmit('update',$this->GetTranslation('Copy Users Permissions'));?>
</form>

