<?php $this->placeholder('optionsHeadline')->set($this->GetTranslation('Module Browser'))?>

<p>
    We are currently working on a module browser.
    This browser will enable you to search a catalog of modules.
    These modules will include both community supported and commercial modules.
</p>
<p>
    The browser will enable you to download and install modules directly through the CMS,
    with no programming required.
</p>
