<dl>
<?php
echo $this->FormRow(
    $this->getTranslation('Select the module page'),
    $this->SelectModulePage('moduleAction', $this->moduleName, null, array('id' => 'modulePage'))
);
?>
</dl>
<script type="text/javascript">
$(document).ready(function() {
    $('#modulePage').change(function() {
        var action = $(this).val();
        $('#moduleFormWrapper').load('/admin/module/render-form/modulename/<?php echo $this->moduleName;?>/moduleaction/' + action);
    });

});
</script>