<?php $this->placeholder("formHeadline")->set($this->GetTranslation("Update User"))?>

<form id="general" action="<?php echo $this->baseUrl;?>/admin/user/edit" method="post">
    <fieldset>
        <legend><?php echo $this->GetTranslation('Account Information');?></legend>
        <?php
        $data = new DSF_Data_Storage();
        $user = $data->get();
        echo $this->formHidden('id',$this->user->id);
            echo $this->FormRow($this->GetTranslation('First Name'), $this->FormText('first_name', $this->user->first_name));
            echo $this->FormRow($this->GetTranslation('Last Name'), $this->FormText('last_name', $this->user->last_name));
            echo $this->FormRow($this->GetTranslation('Email Address'), $this->FormText('email', $this->user->email));
            echo $this->FormRow($this->GetTranslation('Admin Role'), $this->SelectAdminRole('role', $this->user->role));
            echo $this->FormRow('&nbsp;', $this->FormSubmit('update', $this->GetTranslation('Update Account')));
        ?>
    </fieldset>
</form>

<form id="permissions" action="<?php echo $this->baseUrl;?>/admin/user/edit" method="post">
    <fieldset>
        <legend><?php echo $this->GetTranslation('User Permissions');?></legend>
        <?php
            echo $this->formHidden('id',$this->user->id);
            echo $this->RenderAclList($this->userPermissions);
            echo $this->FormSubmit('update_permissions',$this->GetTranslation('Update Permissions'));
        ?>
    </fieldset>
</form>

<form id="password" action="<?php echo $this->baseUrl;?>/admin/user/edit" method="post">
    <fieldset>
        <legend><?php echo $this->GetTranslation('Login Credentials');?></legend>
        <?php
            echo $this->formHidden('id',$this->user->id);
            echo $this->FormRow($this->GetTranslation('Password'), $this->FormPassword('newPassword'));
            echo $this->FormRow($this->GetTranslation('Confirm Password'), $this->FormPassword('newConfirmPassword'));
            echo $this->FormRow('&nbsp;', $this->FormSubmit('admin_user_password', $this->GetTranslation('Update Password')));
        ?>
    </fieldset>
</form>
