<?php $this->placeholder('optionsHeadline')->set($this->getTranslation('User Options'));?>
<?php $this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/jquery/idTabs.js');?>

<ul class="idTabs padding-10">
    <li><?php echo $this->link('Account', '#general', 'vcard_edit.png');?></li>
    <li><?php echo $this->link('Credentials', '#password', 'server_key.png');?></li>
    <li><?php echo $this->link('Permissions', '#permissions', 'application_cascade.png')?></li>
</ul>

<h3><?php echo $this->getTranslation('Copy Permissions');?></h3>
<p class="padding-10"><?php echo $this->getTranslation('If you have another user who already has the same permissions as this user you can copy that user\'s role.');?></p>

<form class="padding-10" action='<?php echo $this->getBaseUrl();?>/admin/user/copy-acl' method="post">
    <?php echo $this->formHidden('id', $this->user->id);?>
    <?php echo $this->selectUser('user_id', null, null, $this->user->id);?>
    <?php echo $this->formSubmit('update', $this->getTranslation('Copy Permissions'));?>
</form>
