<?php 
$this->jQuery()->addJavascriptFile('/scripts/jquery.FCKEditor.pack.js');
$this->jQuery()->onLoadCaptureStart()?>
$('.fckeditor').fck({
	path: '<?php echo $this->baseUrl . "/scripts/fckeditor/" ?>',
	toolbar: 'Digitalus',
	height: 500
});
<?php $this->jQuery()->onLoadCaptureEnd();
$name = $this->form->form->getElement('name');
$label = $name->getLabel();
$name->setLabel($this->getTranslation($label));
echo $this->form->render();
?>

