<?php
$this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/jquery.FCKEditor.pack.js');
$this->jQuery()->onLoadCaptureStart()?>
$('.fckeditor').fck({
	path: '<?php echo $this->getBaseUrl() . "/scripts/fckeditor/" ?>',
	toolbar: 'Digitalus',
	height: 300
});
<?php $this->jQuery()->onLoadCaptureEnd();
$name = $this->form->getElement('name');
$label = $name->getLabel();
$name->setLabel($this->getTranslation($label));
echo $this->form->render();
?>
