<p><?php echo $this->getTranslation('Click the new parent page for this page to move it.')?></p>
<?php 
$this->jQuery()->addJavascriptFile('/scripts/jquery.treeview.js');
$this->jQuery()->addJavascriptFile('/scripts/jquery.cookie.js');
$this->jQuery()->onLoadCaptureStart()?>
    $("#parentTree").treeview({
        persist: "cookie",
        collapsed: true,
        unique: true
    });
<?php $this->jQuery()->onLoadCaptureEnd()?>


<?php
echo $this->RenderFileBrowser(0, '/admin/page/move/id/' . $this->pageId . '/parent/', null, 0, $id = 'parentTree', true);
?>