<?php echo $this->render('./assets/menu.phtml');?>

<div class="formBox">
<h2 class="folder">Current Categories</h2>
<?php 
if($this->categories)
{
	foreach ($this->categories as $category)
	{
		$links[] = "<a href='/mod_news/category/edit/id/{$category->id}'>{$category->title}</a>";
	}
	if(is_array($links))
	{
		echo $this->htmlList($links, null, null, false);
	}
}else{
    echo "<p>There are no news categories to view</p>";
}
?>
</div>	