<?php $this->placeholder("formHeadline")->set($this->GetTranslation("Admininstrator Login"));?>
<p><?php echo $this->GetTranslation('Please enter your username (this is your email address) and password to get started.');?></p>
<form action="<?php echo $this->baseUrl;?>/admin/auth/login" method="post">
<?php 
	echo $this->formHidden('uri', DSF_Uri::get());
	echo $this->FormRow($this->GetTranslation('Username'), $this->FormText('adminUsername',$this->username));
	echo $this->FormRow($this->GetTranslation('Password'), $this->FormPassword('adminPassword'));
	echo $this->FormRow('&nbsp;', $this->FormSubmit('submit',$this->GetTranslation('Log In')));
?>
</form>
