<?php $this->placeholder('optionsHeadline')->set($this->getTranslation('Options'));?>
<ul class="idTabs">
    <li><?php echo $this->link('General', '#site', 'layout_content.png');?></li>
    <li><?php echo $this->link('Content', '#content', 'page_white_stack.png');?></li>
    <li><?php echo $this->link('Meta Data', '#meta', 'page_white_code.png');?></li>
    <li><?php echo $this->link('Internationalization', '#international', 'world.png');?></li>
    <li><?php echo $this->link('Mail', '#mail', 'email.png');?></li>
    <li><?php echo $this->link('Google', '#google', 'google.png');?></li>
</ul>
