<?php $this->placeholder("sidebarHeadline")->set("Site");?>
<p><?php echo $this->GetTranslation('The site sections is where you manage your site.');?></p>

<?php 
$u = new User();
$users = $u->fetchAll(null, 'first_name');
foreach ($users as $user)
{
	$userArray[] = "<a href='/admin/user/open/id/{$user->id}' class='user'>{$user->first_name} {$user->last_name}</a>";
}
?>
<h3><?php echo $this->GetTranslation('Admin Users');?></h3>
<?php 
echo $this->HtmlList($userArray, null, null, false);
?>
<p><a href="/admin/user/create"><?php echo $this->GetTranslation('Create new user');?></a></p>

<h3><?php echo $this->GetTranslation('Site Reports');?></h3>
<ul>
	<li><a href="/admin/report/traffic" class='report'><?php echo $this->GetTranslation('Traffic report');?></a></li>
	<li><a href="/admin/report/admin-access" class='report'><?php echo $this->GetTranslation('Admin access report');?></a></li>
</ul>

<h3><?php echo $this->GetTranslation('Site Console');?></h3>
<p><?php echo $this->GetTranslation('The site console enables you to interact directly with the CMS core. It is for experienced administrators only.');?></p>
<p><a href="/admin/site/console"><?php echo $this->GetTranslation('Open console');?></a></p>




