<?php $this->placeholder('sidebarHeadline')->set($this->getTranslation('Navigation'));

$mdlMenu = new Model_Menu();
$menus = $mdlMenu->getMenus();?>

<ul class="padding-10">
    <li><?php echo $this->link('Main Menu', '/admin/navigation/open/id/0', 'text_list_bullets.png');?></li><?php
    if ($menus) {
        foreach ($menus as $menu) {
            $name = $menu->name;?>
            <li><?php echo $this->link($name, '/admin/navigation/open/id/' . $menu->id, 'text_list_bullets.png');?></li><?php
        }
    }?>
</ul>