<?php
$content  = '';
$cssClass = '';
if (!isset($this->success)) {
    $cssClass = 'note';
    $content .= $this->getTranslation('Please type in Your user name and email address and an email with a link will be sent to Your email address.') . '<br />' . PHP_EOL;
    $content .= $this->getTranslation('If You follow that link You will get to a page where You can easily change Your password.') . PHP_EOL;
} elseif (true == $this->success) {
    $cssClass = 'note';
    $content .= $this->getTranslation('The email was successfully sent. Please follow the link in that email.') . '<br />' . PHP_EOL;
} else {
    $cssClass = 'warning';
    $content .= $this->getTranslation('Something went wrong! Pleas try again!.') . PHP_EOL;
}

if (!empty($content)) {
    echo '<p class="' . $cssClass . '">' . $content . '</p><br />' . PHP_EOL;
}
if (isset($this->form) && !empty($this->form)) {
    echo $this->form;
}