<?php
// error messages
if (!empty($this->error)) {
    echo '<p class="warning">' . $this->error . '</p>';
}
// success messages
if (!empty($this->message)) {
    echo '<p class="note">' . $this->message . '</p>';
}







$content  = '';
$cssClass = '';
if (!empty($content)) {
    echo '<p class="' . $cssClass . '">' . $content . '</p><br />' . PHP_EOL;
}
if (isset($this->form) && !empty($this->form)) {
    echo $this->form;
}