<?php
$form = new Digitalus_Form();

$select = $this->selectGroup('aclRole', $this->getData('aclRole', $this->data->get), null, null, Model_Group::SUPERUSER_ROLE);
if ($select instanceof Zend_Form_Element) {
    $select->setOptions(array(
        'label'     => $this->getTranslation('Select Acl role'),
        'required'  => true,
        'value'     => $this->getData('aclRole', $this->data->get),
        'belongsTo' => 'module'
    ));
}
echo $select;

// type in the email content for the confirmation email
$formTextarea = $form->createElement('textarea', 'email', array(
    'label'     => $this->getTranslation('Confirmation email text'),
    'required'  => true,
    'value'     => $this->getData('email', $this->data->get),
    'attribs'   => array('cols' => 60, 'rows' => 10, 'class' => 'ckeditor'),
    'belongsTo' => 'module',
));
echo $formTextarea;