<?php $this->placeholder('formHeadline')->set($this->getTranslation('Contact Form'))?>

<p><?php echo $this->getTranslation('You can set the following options on the contact form:');?></p>
<ul>
    <li><b><?php echo $this->getTranslation('Recipient');?>:</b> <?php echo $this->getTranslation('who you want to receive the messages');?></li>
    <li><b><?php echo $this->getTranslation('Recipient\'s email');?>:</b> <?php echo $this->getTranslation('the recipient\'s email address');?></li>
</ul>
