<?php $this->placeholder('formHeadline')->set($this->getTranslation('Forward'));?>

<p><?php echo $this->getTranslation('The forward module enables you to forward a page to a subcontent page.');?></p><br />

<fieldset>
    <p><?php echo $this->getTranslation('You can set the following options for the forwarder:');?></p>
    <dt><?php echo $this->getTranslation('Enter forward path') . ':';?></dt><dl><?php echo $this->getTranslation('Forward to page with this path.');?></dl>
</fieldset>