<?php $this->placeholder('optionsHeadline')->set($this->getTranslation('Options'));?>
<?php $this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/jquery/idTabs.js');?>

<ul class="idTabs padding-10">
    <li><?php echo $this->link('Browse Folder',    '#fieldset-mediaSubDirectoriesGroup', 'folder_explore.png')?></li>
    <li><?php echo $this->link('Upload Media',     '#fieldset-mediaUploadGroup',         'page_white_get.png')?></li>
    <li><?php echo $this->link('Create Subfolder', '#fieldset-mediaCreateFolderGroup',   'folder_add.png')?></li>
    <li><?php echo $this->link('Rename Folder',    '#fieldset-mediaRenameFolderGroup',   'folder_edit.png')?></li>
</ul>
