<?php
$grid = new DSF_Interface_Grid('page', 16);
$header = $grid->addElement('header', 16);
    $logo = $header->addElement('header_logo', 10);
    $logo->setAttribute('first', true);
    $top = $header->addElement('header_top',6);
    $top->setAttribute('last', true);
$header->setAttribute('clear', true);

$nav = $grid->addElement('nav', 16);
$nav->setAttribute('clear', true);

$body = $grid->addElement('body', 16);
    $content = $body->addElement('content', 13);
    $content->setAttribute('first', true);
    $sidebarRight = $body->addElement('sidebar_right', 3);
    $sidebarRight->setAttribute('last', true);
$body->setAttribute('clear', true);

$footer = $grid->addElement('footer', 16);
$footer->setAttribute('clear', true);

$this->placeholder('header_logo_content')->set(
    "<a href='http://digitaluscms.com'><img src='" . $this->baseUrl . "/images/logo.png' alt='Powered by Digitalus CMS' /></a>"
);

$this->placeholder('header_top_content')->set(
    ''
);

if (is_object($this->page) && $this->isError != true) {
    $this->content = $this->RenderContentTemplate($this->page->getContentTemplate(), $this->page->getContent());
    $this->submenu = $this->RenderSubmenu();
}

$this->placeholder('content_content')->set($this->content);

$this->placeholder('nav_content')->set(
    $this->RenderMenu(0)
);

##Not used
#$this->placeholder('sidebar_left_content')->set(
#    $this->submenu
#);

$this->placeholder('sidebar_right_content')->set($this->GetTranslation('language') . $this->ListLanguageLinks());

$this->placeholder('footer_content')->set(
    $this->partial('partials/footer.phtml')
);

echo $grid->render();
