<?php $this->placeholder('optionsHeadline')->set($this->getTranslation('Options'));?>
<?php $this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/jquery/idTabs.js');?>
<ul class="idTabs padding-10">
    <li><?php echo $this->link('General', '#fieldset-siteGroup', 'layout_content.png');?></li>
    <li><?php echo $this->link('Content', '#fieldset-contentGroup', 'page_white_stack.png');?></li>
    <li><?php echo $this->link('Design', '#fieldset-designGroup', 'palette.png');?></li>
    <li><?php echo $this->link('Meta Data', '#fieldset-metaGroup', 'page_white_code.png');?></li>
    <li><?php echo $this->link('Internationalization', '#fieldset-internationalGroup', 'world.png');?></li>
    <li><?php echo $this->link('Mail', '#fieldset-mailGroup', 'email.png');?></li>
    <li><?php echo $this->link('Google', '#fieldset-googleGroup', 'google.png');?></li>
</ul>
