<?php
$this->placeholder('formHeadline')->set($this->GetTranslation('My Dashboard'));
?>

<form action="<?php echo $this->baseUrl;?>/admin/user/update-my-account" method="post">
    <fieldset class="formColumn">
        <legend><?php echo $this->GetTranslation('My Account');?></legend>
        <?php
            $u = new User();
            $user = $u->getCurrentUser();
            echo $this->formHidden('id',$user->id);
            echo $this->FormRow($this->GetTranslation('First Name'), $this->formText('first_name' , $this->identity->first_name));
            echo $this->FormRow($this->GetTranslation('Last Name'), $this->formText('last_name', $this->identity->last_name));
            echo $this->FormRow($this->GetTranslation('Email'), $this->formText('email', $this->identity->email));
            echo $this->FormRow($this->formCheckbox('update_password'), $this->GetTranslation('Update password?'));
            echo $this->FormRow($this->GetTranslation('Password'), $this->formPassword('password'));
            echo $this->FormRow($this->GetTranslation('Confirm'), $this->formPassword('confirmation'));
            echo $this->formSubmit('submit',$this->GetTranslation('Update My Account'));
        ?>
    </fieldset>
</form>


<fieldset class="formColumn">
    <legend><?php echo $this->GetTranslation('My Bookmarks');?></legend>
    <?php if ($this->bookmarks) {
        ?>
    <ul>
    <?php foreach ($this->bookmarks as $bookmark) {?>
        <li><?php
            echo $this->link(null, $this->baseUrl . '/admin/index/delete-bookmark/id/' . $bookmark->id, 'link_delete.png', 'clear');
            $content = $bookmark->content;
            if (strpos($content, 'mod_') == 0) {
                $content = str_replace('mod_', '', $content);
                $content = DSF_Toolbox_String::stripUnderscores($content);
                $content = 'mod_' . $content;
            }
            echo $this->link($bookmark->node, $this->baseUrl . '/' . $content);
        ?></li>
    <?php } ?>
    </ul>
    <?php } else {
            echo $this->GetTranslation('You do not have any bookmarks.');
    } ?>
</fieldset>

<form action="<?php echo $this->baseUrl?>/admin/index/notes" method="post" id="notes">
    <fieldset class="clearBoth">
        <legend><?php echo $this->GetTranslation('My Writeboard');?></legend>
        <p><?php echo $this->GetTranslation('The writeboard is a personal spot for you to keep notes about your site.');?></p>
            <?php
                echo $this->formTextarea('content', $this->notes->content);
                echo $this->formSubmit('submit',$this->GetTranslation('Save My Writeboard'));
            ?>
    </fieldset>
</form>
