<?php
$this->placeholder('optionsHeadline')->Set($this->translate('My Content'));
echo $this->RenderText('The following pages are the pages that you have recently created.', 'p class="padding-10"');
?>
<?php
if ($this->pages) {
    ?>
    <ul class="padding-10">
    <?php foreach ($this->pages as $page) {
        if (isset($page->label) && !empty($page->label)) {
            $label = $page->label;
        } else {
            $label = $page->name;
        } ?>
        <li class="page">
            <?php echo $this->link($label, '/admin/page/edit/id/' . $page->id, 'page_white_text.png');?>
        </li>
    <?php } ?>
    </ul>
<?php }

echo $this->RenderText('These are the modules that you are working with.', 'p class="padding-10"');
echo $this->render('./module/partials/my-modules.phtml');
