<p><?php echo $this->GetTranslation('Digitalus CMS is a community supported open source project. To learn more about the project check out:');?>:</p>
<ul>
    <li><a href="http://digitaluscms.com" target="_blank"><?php echo $this->GetTranslation('Site');?></a></li>
    <li><a href="http://wiki.digitaluscms.com" target="_blank"><?php echo $this->GetTranslation('Wiki');?></a></li>
    <li><a href="http://forum.digitaluscms.com" target="_blank"><?php echo $this->GetTranslation('Forum');?></a></li>
</ul>
<p></p>

<h3><?php echo $this->GetTranslation('Training and Support');?></h3>
<p><?php echo $this->GetTranslation('If you need any help building or managing your site check out our');?> <a href="http://digitaluscms.com/support" target="_blank"><?php echo $this->GetTranslation('support options');?></a></p>
