<?php
$this->placeholder('formHeadline')->set($this->getTranslation('My Dashboard'));
?>

<form action="<?php echo $this->getBaseUrl();?>/admin/user/update-my-account" method="post">
    <fieldset class="formColumn">
        <legend><?php echo $this->getTranslation('My Account');?></legend>
        <dl>
        <?php
            $u = new Model_User();
            $user = $u->getCurrentUser();
            echo '<dt>' . $this->formHidden('id', $user->id) . '</dt>';
            echo $this->FormRow($this->getTranslation('First Name'), $this->formText('first_name' , $this->identity->first_name));
            echo $this->FormRow($this->getTranslation('Last Name'), $this->formText('last_name', $this->identity->last_name));
            echo $this->FormRow($this->getTranslation('Email'), $this->formText('email', $this->identity->email));
            echo $this->FormRow($this->formCheckbox('update_password'), $this->getTranslation('Update password?'));
            echo $this->FormRow($this->getTranslation('Password'), $this->formPassword('password'));
            echo $this->FormRow($this->getTranslation('Confirm'), $this->formPassword('confirmation'));
            echo $this->formSubmit('submit',$this->getTranslation('Update My Account'));
        ?>
        </dl>
    </fieldset>
</form>


<fieldset class="formColumn">
    <legend><?php echo $this->getTranslation('My Bookmarks');?></legend>
    <?php if ($this->bookmarks) {
        ?>
    <ul>
    <?php foreach ($this->bookmarks as $bookmark) {?>
        <li><?php
            echo $this->link(null, '/admin/index/delete-bookmark/id/' . $bookmark->id, 'link_delete.png', 'clear');
            $content = $bookmark->content;
            if (strpos($content, 'mod_') === 0) {
                $content = str_replace('mod_', '', $content);
                $content = Digitalus_Toolbox_String::stripUnderscores($content);
                $content = 'mod_' . $content;
            } else {
                $content = Digitalus_Toolbox_String::stripUnderscores($content);
            }
            echo $this->link($bookmark->node, '/' . $content);
        ?></li>
    <?php } ?>
    </ul>
    <?php } else {
            echo $this->getTranslation('You do not have any bookmarks.');
    } ?>
</fieldset>

<form action="<?php echo $this->getBaseUrl()?>/admin/index/notes" method="post" id="notes">
    <fieldset class="clearBoth">
        <legend><?php echo $this->getTranslation('My Writeboard');?></legend>
        <p><?php echo $this->getTranslation('The writeboard is a personal spot for you to keep notes about your site.');?></p>
            <?php
                echo $this->formTextarea('content', $this->notes->content);
                echo $this->formSubmit('submit',$this->getTranslation('Save My Writeboard'));
            ?>
    </fieldset>
</form>


