<?php $this->placeholder('sidebarHeadline')->set($this->getTranslation('Home'))?>

<p class="padding-10"><?php echo $this->getTranslation('Digitalus CMS is a community supported open source project. To learn more about the project check out');?>:</p>
<ul class="padding-10">
    <li><?php echo $this->link('Digitalus Site', 'http://digitaluscms.com', 'house.png');?></li>
    <li><?php echo $this->link('Wiki', 'http://wiki.digitaluscms.com', 'page_white_stack.png');?></li>
    <li><?php echo $this->link('Forum', 'http://forum.digitaluscms.com', 'group.png');?></li>
</ul>
