<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Digitalus CMS <?php echo $this->escape($this->title); ?></title>
<?php 
//style sheets
$this->headLink()->appendStylesheet('/templates/admin/admin/styles/layout.css')
                 ->appendStylesheet('/templates/admin/admin/styles/text.css') 
                 ->appendStylesheet('/templates/admin/admin/styles/nav.css')
                 ->appendStylesheet('/templates/admin/admin/styles/style.css')
                 ->appendStylesheet('/templates/admin/admin/styles/form.css')
                 ->appendStylesheet('/public/styles/datePicker.css') 
                 ->appendStylesheet('/public/styles/adminForms.css') 
                 ->appendStylesheet('/public/styles/filetree.css') 
                 ->appendStylesheet('/public/styles/menutree.css') 
                 ->appendStylesheet('/public/styles/jquery.treeview.css') 
                 ->appendStylesheet('/public/styles/icons.css') 
                 ->appendStylesheet('/public/styles/spreadsheet.css') 
                 ->appendStylesheet('/public/styles/sortable.css'); 
echo $this->headLink();

//javascripts
$this->headScript()->appendFile('/public/scripts/jquery-1.2.1.pack.js')
                   ->appendFile('/public/scripts/interface.js')
                   ->appendFile('/public/scripts/jqueryTooltip.js')
                   ->appendFile('/public/scripts/jqueryDatePicker.js')
                   ->appendFile('/public/scripts/jquery.dateCompletion.js')
                   ->appendFile('/public/scripts/jquery.treeview.js')
                   ->appendFile('/public/scripts/idTabs.js')
                   ->appendFile('/public/scripts/jquery.cookie.js');
echo $this->headScript();

//jquery block
$this->placeholder('jquery')->captureStart();
?>

$('#menu_<?php echo $this->adminSection;?>').addClass('selectedNav'); 

$.datePicker.setDateFormat('myd', '-');

$('input.date-picker').datePicker({startDate:'01-01-2008'});
$("input.date-picker").blur(function () {
    var value = $(this).val();

    $(this).dateCompletion(value);
});

$('.showTip').Tooltip({showURL: false, showBody: " - "});

$(".message_box").bind("click",function(){
       $(this).fadeOut("slow");
  });

	  $('a.deleteConfirm').bind('click',function(){
  	var t = $(this).attr('title');
  	var answer = confirm('Are you sure you want to delete this ' + t + "?");
    if(!answer){return false;}
  });
  
$('.spreadsheet tr:odd').addClass('oddRow');	
  
<?php $this->placeholder('jquery')->captureEnd();?>	

</head>

<body>
<div id="pageWrapper">
	<div id="header">
		<a id='logo' href="#">
			<img src="/templates/admin/admin/images/logo.png" alt="Digitalus CMS" />
		</a>
		<div id="top">
			<div id="adminUser">
                <?php echo $this->placeholder('currentAdmin');?>
			</div>

		</div>
	</div>
	<?php echo $this->placeholder('adminMenu');?>
	<div id="page" class="clearFix">
			<?php echo $this->RenderAlert();?>
			<?php if(!empty($this->fullPageForm)){ //using this you can set the whole page to be a form?>
				<form action='<?php echo $this->fullPageForm;?>' method='post' enctype="multipart/form-data">
			<?php } ?>
				<div id="leftPane">
					<?php echo $this->placeholder('sidebar');?>
				</div>
				<div id="centerPane">
			    	<?php echo $this->placeholder('mainForm');?>
				</div>
			<?php if(!empty($this->fullPageForm)){ //using this you can set the whole page to be a form?>
				</form>
			<?php } ?>
	</div>
	<p id="copyright">&copy; 2008 Digitalus Content Management LLC</p>
</div>
<script type="text/javascript">
$(document).ready(function() {
	  <?php echo $this->placeholder('jquery');?>
});
</script>
</body>
