<?php
echo $this->FormRow('Enter the recipient:', $this->formText($this->element . '[recipient]', $this->formParams['recipient']));
echo $this->FormRow('Enter the recipients email:', $this->formText($this->element . '[email]', $this->formParams['email']));
echo $this->FormRow('Autoresponse subject (optional):', $this->formText($this->element . '[autoresponse_subject]', $this->formParams['autoresponse_subject'], array('class' => 'med')));
echo $this->FormRow('Autoresponse message(optional):', $this->formTextarea($this->element . '[autoresponse_message]', $this->formParams['autoresponse_message'], array('class' => 'med')));
echo $this->FormRow('Success message:', $this->formText($this->element . '[successMessage]', $this->formParams['successMessage'], array('class' => 'med')));
echo $this->FormRow('Error message:', $this->formText($this->element . '[errorMessage]', $this->formParams['errorMessage'], array('class' => 'med')));
?>

