<?php $this->placeholder('formHeadline')->set($this->getTranslation('Search Module'));

if (isset($this->errorMessage) && !empty($this->errorMessage)) { ?>
    <p class="notice"><?php
        echo $this->getTranslation($this->errorMessage) . '<br />';
        echo '<strong>' . $this->indexPath . '</strong>'; ?>
    </p><?php
} ?>
<p><?php echo $this->getTranslation('The search module utilizes the Lucene search engine to build, manage and query search indexes on your site.');?></p>
<p><?php echo $this->getTranslation('Rebuilding the search index is very processor intensive, so Digitalus does not rebuild it each time you update your site. When you update your site open this module, and click the Rebuild Search Index link.');?></p>