<?php $this->placeholder('formHeadline')->set($this->GetTranslation('Update Site Settings'));?>
<form action="<?php echo $this->baseUrl; ?>/admin/site/edit" method="post" id='site'>
    <fieldset>
        <legend><?php echo $this->GetTranslation('General settings');?></legend>
        <?php
            echo $this->FormRow($this->GetTranslation('Site name'), $this->FormText('setting[name]', $this->settings->name));
            echo $this->FormRow($this->GetTranslation('Title separator'), $this->FormText('setting[title_separator]', $this->settings->title_separator, array('class' => 'med')));
            echo $this->FormRow($this->GetTranslation('Status'), $this->formCheckbox('setting[online]', intval($this->settings->online)) . ' ' . $this->GetTranslation('Site is online'));
            echo $this->FormRow('&nbsp;', $this->FormSubmit('site', $this->GetTranslation('Update General Site Settings')));
        ?>
    </fieldset>
</form>

<form action="<?php echo $this->baseUrl; ?>/admin/site/edit" method="post" id='content'>
    <fieldset>
        <legend><?php echo $this->GetTranslation('Managing Content');?></legend>
    <?php
        echo $this->FormRow(
            $this->GetTranslation('Home Page'),
            $this->SelectPage('setting[home_page]', $this->settings->home_page)
        );
        echo $this->FormRow(
            $this->GetTranslation('404 Page'),
            $this->SelectPage('setting[page_not_found]', $this->settings->page_not_found)
        );
        echo $this->FormRow(
            $this->GetTranslation('Site Offline Page'),
            $this->SelectPage('setting[offline_page]', $this->settings->offline_page)
        );
        echo $this->FormRow($this->GetTranslation('Menu links'),
            $this->formCheckbox('setting[add_menu_links]', intval($this->settings->add_menu_links)) . ' ' .
            $this->GetTranslation('Automatically add menu links')
        );
        echo $this->FormRow('&nbsp;', $this->FormSubmit('content', $this->GetTranslation('Update Content Settings')));
    ?>
    </fieldset>
</form>

<form action="<?php echo $this->baseUrl; ?>/admin/site/edit" method="post" id='meta'>
    <fieldset>
        <legend><?php echo $this->GetTranslation('Meta Data');?></legend>
    <?php
        echo $this->FormRow($this->GetTranslation('Doc Type'), $this->selectDoctype('setting[doc_type]', $this->settings->doc_type));
        echo $this->FormRow($this->GetTranslation('Default charset'), $this->FormText('setting[default_charset]', $this->settings->default_charset));
        echo $this->FormRow('&nbsp;', $this->FormSubmit('meta', $this->GetTranslation('Update Page Meta Data')));
    ?>
    </fieldset>
</form>

<form action="<?php echo $this->baseUrl; ?>/admin/site/edit" method="post" id='international'>
    <fieldset>
        <legend><?php echo $this->GetTranslation('Internationalization');?></legend>
    <?php
        echo $this->FormRow($this->GetTranslation('Default language'), $this->selectLanguage('setting[default_language]', $this->settings->default_language));
        // the admin language should default to the setting in config
        if (isset($this->settings->admin_language)) {
            $adminLanguage = $this->settings->admin_language;
        } else {
           $config = Zend_Registry::get('config'); 
           $adminLanguage = $config->language->defaultLocale;
        }
        
        echo $this->FormRow($this->GetTranslation('Admin language'), $this->selectLanguage('setting[admin_language]', $adminLanguage));
        echo $this->FormRow('&nbsp;', $this->FormSubmit('language', $this->GetTranslation('Update Internationalization Settings')));
    ?>
    </fieldset>
</form>

<form action="<?php echo $this->baseUrl; ?>/admin/site/edit" method="post" id='mail'>
    <fieldset>
        <legend><?php echo $this->GetTranslation('Mail Settings');?></legend>
    <?php
        echo $this->FormRow($this->GetTranslation('Default email address'), $this->FormText('setting[default_email]', $this->settings->default_email));
        echo $this->FormRow($this->GetTranslation('Default sender'), $this->FormText('setting[default_email_sender]', $this->settings->default_email_sender));
        echo $this->FormRow(
            $this->GetTranslation('Transport'),
            $this->formCheckbox('setting[use_smtp_mail]', intval($this->settings->use_smtp_mail)) . ' ' . $this->GetTranslation('Use SMTP transport '));
        echo $this->FormRow($this->GetTranslation('SMTP host'), $this->FormText('setting[smtp_host]', $this->settings->smtp_host));
        echo $this->FormRow($this->GetTranslation('SMTP username'), $this->FormText('setting[smtp_username]', $this->settings->smtp_username));
        echo $this->FormRow($this->GetTranslation('SMTP password'), $this->FormPassword('setting[smtp_password]', $this->settings->smtp_password));
        echo $this->FormRow('&nbsp;', $this->FormSubmit('mail', $this->GetTranslation('Update Mail Settings')));
        echo $this->FormRow('&nbsp;', $this->link($this->GetTranslation('Send test message'), '/admin/site/mail-test', 'email_go.png'));
    ?>
    </fieldset>
</form>

<form action="<?php echo $this->baseUrl; ?>/admin/site/edit" method="post" id='google'>
    <fieldset>
        <legend><?php echo $this->GetTranslation('Google Integration');?></legend>
    <?php
        echo $this->FormRow($this->GetTranslation('Verification code'), $this->FormTextarea('setting[google_verify]', $this->settings->google_verify, array('class' => 'med')));
        echo $this->FormRow($this->GetTranslation('Tracking code'), $this->FormTextarea('setting[google_tracking]', $this->settings->google_tracking, array('class' => 'med')));
        echo $this->FormRow('&nbsp;', $this->FormSubmit('google', $this->GetTranslation('Update Google Settings')));
    ?>
    </fieldset>
</form>
