<?php $this->placeholder('formHeadline')->set($this->getTranslation('Update Group'));

$this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/jquery/jquery.treeview.min.js');
$this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/jquery/jquery.cookie.js');

$this->jQuery()->onLoadCaptureStart();?>
    $(".acl_resources").treeview({
        persist:   'cookie',
        collapsed: true,
        unique:    true
    });<?php
$this->jQuery()->onLoadCaptureEnd();

echo $this->form;