<div class="formBox">
    <h2><?php echo $this->getTranslation('Admin Access Log');?></h2>
    <table class='spreadsheet' cellpadding="0" cellspacing="0">
        <tr>
            <th><?php echo $this->getTranslation('Date');?></th>
            <th><?php echo $this->getTranslation('Name');?></th>
            <th><?php echo $this->getTranslation('Page');?></th>
        </tr><?php
        foreach ($this->accessLog as $entry) { ?>
        <tr>
            <td><?php echo $entry->date;?>&nbsp;</td>
            <td><?php echo $entry->first_name . ' ' . $entry->last_name;?>&nbsp;</td>
            <td><?php echo $entry->page;?>&nbsp;</td>
        </tr><?php
        } ?>
    </table>

</div>
