<?php
$total = 0;
?>
<h2 class="report"><?php echo $this->getTranslation('Weekly Summary');?></h2><?php
foreach ($this->hitsThisWeek as $day) { ?>
<p><b><?php echo $this->getTranslation('Day');?></b> <?php echo $day->day;?> - <b><?php echo $this->getTranslation('Hits');?></b> <?php echo $day->unique_hits;?></p>
<?php $total = $day->unique_hits;
} ?>
<p><b><?php echo $this->getTranslation('Total');?>:</b> <?php echo $total; $total = 0;?></p>

<h2 class="report"><?php echo $this->getTranslation('Traffic History');?></h2><?php
foreach ($this->hitsByWeek as $week) { ?>
<p><b><?php echo $this->getTranslation('Week');?></b> <?php echo $week->week;?> - <b><?php echo $this->getTranslation('Hits');?></b> <?php echo $week->unique_hits;?></p>
<?php $total += $day->unique_hits;
} ?>
<p><b><?php echo $this->getTranslation('Total');?>:</b> <?php echo $total;?></p>
