<form class="formBox" action="/mod_contact/index/ask-question" method="POST">
    <h2 class="settings">Settings</h2>
    <?php
        echo $this->FormRow("Enter the recipient email for your user's questions", $this->formText('setting[recipient]', $this->settings->recipient));
        echo $this->Note("The autoresponse needs to be implemented on the front end.");
        echo $this->FormRow("&nbsp;", $this->formCheckbox('setting[autoResponse]', $this->settings->autoResponse) . " Check here if you want to send an autoresponse to the user.");
        echo $this->FormRow("Enter the autoresponse subject", $this->formText('setting[autoSubject]', $this->settings->autoSubject, array('class' => 'med')));
        echo $this->FormRow("Enter the autoresponse message", $this->formTextarea('setting[autoMessage]', $this->settings->autoMessage, array('class' => 'med')));
        
        echo $this->FormRow('&nbsp', $this->formSubmit('update', "Update Settings"));
    ?>
</form>