<?php $this->placeholder('formHeadline')->set($this->GetTranslation('Contact Form'))?>

<p><?php echo $this->GetTranslation('You can set the following options on the contact form:');?></p>
<ul>
    <li><b><?php echo $this->GetTranslation('Recipient');?>:</b> <?php echo $this->GetTranslation('who you want to receive the messages');?></li>
    <li><b><?php echo $this->GetTranslation('Recipient\'s email');?>:</b> <?php echo $this->GetTranslation('the recipient\'s email address');?></li>
</ul>
