<?php $this->placeholder('formHeadline')->set($this->GetTranslation('Contact Form'))?>

<p>You can set the following options on the contact form:</p>
<ul>
<li><b>Recipient</b> -> who you want to recieve the messages</li>
<li><b>Recipient's email</b> -> the recipient's email address</li>
<li><b>Autoresponse (optional)</b>
    <ul>
        <li><b>Subject</b> -> the subject of the autoresponse message</li>
        <li><b>Message</b> -> the message you want to send as the autoresponse body.  note that if this is not set the system will not send autoresponses</li>
    </ul>
</li>
<li><b>Success message</b> -> this message will be displayed after a message was sent successfully</li>
<li><b>Error message</b> -> this message will be displayed if there is an error sending the message</li>
</ul>


