<?php 
echo '<?xml version="1.0" encoding="' . $this->placeholder('charset') . '" ?>';
echo $this->doctype() 
?>
<html>
	<head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    <?php     
	        echo $this->placeholder('google_verify');	
			echo $this->headTitle();
			echo $this->headScript();	    	
			echo $this->headLink();
	    ?>
	    <style type="text/css">
			<?php echo $this->placeholder('inlineStyles'); ?>
	    </style>
	</head>
	
	<body>
		<?php 
		    echo $this->layout()->page;
		    echo $this->placeholder('google_tracking');
	    ?>
	</body>
</html>