<?php
/*
$form = new Digitalus_Form();

$select = $this->selectGroup('aclRole', $this->getData('aclRole', $this->data->get), null, null, Model_Group::SUPERUSER_ROLE);
if ($select instanceof Zend_Form_Element) {
    $select->setLabel($this->getTranslation('Select Acl role'))
           ->setBelongsTo($this->getData('element', $this->data->get))
           ->setValue($this->getData('aclRole', $this->data->get));
}
echo $select;

// type in the email content for the confirmation email
$formTextarea = $form->createElement('textarea', 'email', array(
    'label'     => $this->getTranslation('Confirmation email text'),
    'value'     => $this->getData('email', $this->data->get),
    'attribs'   => array('cols' => 60, 'rows' => 10, 'class' => 'ckeditor'),
    'belongsTo' => $this->getData('element', $this->data->get),
));
echo $formTextarea;
*/