<?php
$form = new Digitalus_Form();

// type in the email content for the new-password email
$formTextarea = $form->createElement('textarea', 'email', array(
    'label'     => $this->getTranslation('New password email text'),
    'required'  => true,
    'value'     => $this->getData('email', $this->data->get),
    'attribs'   => array('cols' => 60, 'rows' => 10, 'class' => 'ckeditor'),
    'belongsTo' => $this->getData('element', $this->data->get),
));
echo $formTextarea;