<?php if(!$this->center->id){ ?>
<p>Sorry, there was an error loading your news center</p>
<?php }else{ ?>
<h2><?php echo $this->center->title;?></h2>
<?php echo $this->RenderContent('content', $this->center);?>

<h2>Articles</h2>
<?php 
if(count($this->items) > 0){
    foreach ($this->items as $item){
?>
<h3><a href="<?php echo $this->CleanUri(true);?>/p/openItem/<?php echo $item->id;?>"><?php echo $item->title;?></a></h3>
<p><?php echo $this->RenderContent('content', $item, 50);?></p>
<?php }}else{ ?>
<p>There are no articles in this news center</p>
<?php 
}
}
