<div class='pageContent'>
    <h1>
        <?php
            $headlineOptions = array(
                'label'     => $this->getTranslation('Headline'),
                'required'  => true,
                'size'      => 50
            );
            $contentHeadline = null;
            if (isset($this->content['headline'])) {
                $contentHeadline = $this->content['headline'];
            }
            echo $this->contentControl('text', 'headline', $contentHeadline, $headlineOptions);
        ?>
    </h1>
    <div class='contentWrapper'>
        <?php
            $contentOptions = array(
                'label'     => $this->getTranslation('Content'),
                'required'  => true,
                'cols'      => 60,
                'rows'      => 4
            );
            $content = null;
            if (isset($this->content['content'])) {
                $content = $this->content['content'];
            }
            echo $this->contentControl('fckeditor', 'content', $content, $contentOptions);
        ?>
    </div>
</div>