<div class='pageContent'>
	<h1>
	    <?php 
            $headlineOptions = array(
                'label'		=> 'Headline',
                'required'	=> TRUE,
                'size'		=> 50
            );
	        echo $this->contentControl('text', 'headline', $this->content['headline'], $headlineOptions); 
        ?>
    </h1>
	<div class='contentWrapper'>
	    <?php 
            $contentOptions = array(
                'label'		=> 'Content',
                'required'	=> TRUE,
                'cols'		=> 60,
                'rows'		=> 4
            );
	        echo $this->contentControl('fckeditor', 'content', $this->content['content'], $contentOptions); 
        ?>
	</div>
</div>