<h1>
    <?php
        $headlineOptions = array(
            'label'     => $this->getTranslation('Headline'),
            'required'  => true,
            'size'      => 50
        );
        $contentHeadline = null;
        if (isset($this->content['headline'])) {
            $contentHeadline = $this->content['headline'];
        }
        echo $this->contentControl('text', 'headline', $contentHeadline, $headlineOptions);
    ?>
</h1>
<div class="contentWrapper">
    <?php
        $contentAboveOptions = array(
            'label'     => $this->getTranslation('Content Above'),
            'cols'      => 60,
            'rows'      => 4
        );
        $contentAbove = null;
        if (isset($this->content['content_above'])) {
            $contentAbove = $this->content['content_above'];
        }
        echo $this->contentControl('textarea', 'content_above', $contentAbove, $contentAboveOptions);
    ?>
</div>
<div class="module">
    <?php
        $moduleOptions = array(
            'label'     => $this->getTranslation('Select Module'),
            'required'  => true
        );
        $contentModule = null;
        if (isset($this->content['module'])) {
            $contentModule = $this->content['module'];
        }
        echo $this->moduleControl('module', $contentModule, $moduleOptions);
    ?>
</div>
<div class="contentWrapper">
    <?php
        $contentBelowOptions = array(
            'label'     => $this->getTranslation('Content Below'),
            'cols'      => 60,
            'rows'      => 4
        );
        $contentBelow = null;
        if (isset($this->content['content_below'])) {
            $contentBelow = $this->content['content_below'];
        }
        echo $this->contentControl('textarea', 'content_below', $contentBelow, $contentBelowOptions);
    ?>
</div>