<?php $this->placeholder("optionsHeadline")->set($this->getTranslation('Options'))?>

<ul class="idTabs">
    <li><?php echo $this->link('Browse Folder',    '#browse',    'folder_explore.png')?></li>
    <li><?php echo $this->link('Upload Media',     '#upload',    'page_white_get.png')?></li>
    <li><?php echo $this->link('Create Subfolder', '#subfolder', 'folder_add.png')?></li>
    <li><?php echo $this->link('Rename Folder',    '#rename',    'folder_edit.png')?></li>
</ul>
