<?php $this->placeholder('formHeadline')->set($this->GetTranslation('Open Folder'))?>
<fieldset>
    <?php
        $pathParts[] = $this->pathToMedia;
        if (is_array($this->folderPathParts)) {
            foreach ($this->folderPathParts as $path => $label) {
                $pathParts[] = "<a href='{$this->getBaseUrl()}/admin/media/open-folder/folder/{$path}'>{$label}</a>";
            }
        }
    ?>
    <legend><?php echo $this->GetTranslation('Current Folder');?></legend>
    <p><?php echo $this->getBaseUrl() . '/' . implode('/', $pathParts);?></p>
</fieldset>

<fieldset id='browse'>
    <legend><?php echo $this->GetTranslation('Current folder contents');?></legend>
    <?php
        $data = array(
            'filepath'  => $this->filesystemPath,
            'mediapath' => $this->mediaPath,
            'files'     => $this->files,
            'folders'   => $this->folders
        );
        echo $this->partial('media/partials/file-list.phtml', $data);
    ?>
</fieldset>

<fieldset id='upload'>
    <legend><?php echo $this->GetTranslation('Upload Files');?></legend>
    <?php
        $data = array(
            'action'    => 'upload',
            'filepath'  => $this->filesystemPath,
            'mediapath' => $this->mediaPath,
        );
        echo $this->partial('media/partials/upload-files.phtml', $data);
    ?>
</fieldset>

<fieldset id='subfolder'>
    <legend><?php echo $this->GetTranslation('Create Subfolder');?></legend>
    <?php echo $this->render('media/partials/create-subfolder.phtml'); ?>
</fieldset>

<fieldset id='rename'>
    <legend><?php echo $this->GetTranslation('Rename folder');?></legend>
    <?php
        $data = array(
            'filepath'  => $this->filesystemPath,
            'mediapath' => $this->mediaPath,
            'label'     => $label
        );
        echo $this->partial('media/partials/rename-folder.phtml', $data);
    ?>
</fieldset>

<?php
$this->placeholder('jquery')->captureStart();
?>
$('#multi_upload').MultiFile();

<?php $this->placeholder('jquery')->captureEnd();?>