<h2><?php echo $this->getTranslation('Installation Successfull!');?></h2>
<p><?php echo $this->getTranslation('Digitalus CMS was successfully installed on your domain.');?></p>
<p><?php echo $this->getTranslation('Before you use it you must completely delete the <strong>install</strong> folder, as in this screenshot:</p>');?>
<img src="./images/assets/screenshots/delete-install-folder.png" alt="screenshot" />
<p><?php echo $this->getTranslation('Once that folder is deleted Digitalus will automatically load when you visit this domain.');?></p>