<?php
if(empty($this->placeholder('charset'))) {
   $this->placeholder('charset') = 'utf-8'; 
}
echo '<?xml version="1.0" encoding="' . $this->placeholder('charset') . '" ?>' . PHP_EOL;
echo $this->doctype() . PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>
    <?php echo $this->GetTranslation('Digitalus CMS') . $this->escape($this->title); ?></title>
<?php
//style sheets
$this->headLink()->appendStylesheet($this->baseUrl . '/skins/digitalus-1-5/styles/layout.css')
                 ->appendStylesheet($this->baseUrl . '/skins/digitalus-1-5/styles/text.css')
                 ->appendStylesheet($this->baseUrl . '/skins/digitalus-1-5/styles/nav.css')
                 ->appendStylesheet($this->baseUrl . '/skins/digitalus-1-5/styles/style.css')
                 ->appendStylesheet($this->baseUrl . '/skins/digitalus-1-5/styles/form.css')
                 ->appendStylesheet($this->baseUrl . '/styles/datePicker.css')
                 ->appendStylesheet($this->baseUrl . '/styles/adminForms.css')
                 ->appendStylesheet($this->baseUrl . '/styles/filetree.css')
                 ->appendStylesheet($this->baseUrl . '/styles/menutree.css')
                 ->appendStylesheet($this->baseUrl . '/styles/jquery.treeview.css')
                 ->appendStylesheet($this->baseUrl . '/styles/spreadsheet.css')
                 ->appendStylesheet($this->baseUrl . '/styles/jquery.wysiwyg.css')
                 ->appendStylesheet($this->baseUrl . '/styles/sortable.css');
echo $this->headLink();

//javascripts
$this->headScript()->prependFile($this->baseUrl . '/scripts/jquery.pack.js')
                   ->appendFile($this->baseUrl . '/scripts/interface.js')
                   ->appendFile($this->baseUrl . '/scripts/jqueryTooltip.js')
                   ->appendFile($this->baseUrl . '/scripts/jqueryDatePicker.js')
                   ->appendFile($this->baseUrl . '/scripts/jquery.dateCompletion.js')
                   ->appendFile($this->baseUrl . '/scripts/jquery.treeview.js')
                   ->appendFile($this->baseUrl . '/scripts/idTabs.js')
                   ->appendFile($this->baseUrl . '/scripts/jquery.wysiwyg.js')
                   ->appendFile($this->baseUrl . '/scripts/jquery.multifile.js')
                   ->appendFile($this->baseUrl . '/scripts/jquery.cookie.js');
echo $this->headScript();

//jquery block
$this->placeholder('baseJquery')->captureStart();
?>
$(".message_box").bind("click",function(){
       $(this).fadeOut("slow");
  });

      $('a.delete').bind('click',function(){
    var answer = confirm('Are you sure you want to delete this?');
    if(!answer){return false;}
  });

$('a.add_to_my_bookmarks').click(function(){
    var label = prompt('Bookmark label:');
    if(label){
        var url = $(this).attr('href');
        url += '/label/' + label;
        if(jQuery.get(url)){
            alert('Your bookmark was successfully saved.');
        }
    }
    return false;
});

$('.wysiwyg').wysiwyg({
    controls : {
        separator04 : { visible : true },

        insertOrderedList : { visible : true },
        insertUnorderedList : { visible : true },
        alert : {
            visible   : true,
            exec      : function() { alert('Hello World'); },
            className : 'alert'
        }

    }
});

$('.spreadsheet tr:odd').addClass('oddRow');

<?php $this->placeholder('baseJquery')->captureEnd();?>
</head>

<body>
    <div id="page">
        <div id="header">
            <?php
               echo $this->CurrentAdminUser();
               echo $this->RenderAdminMenu();
           ?>
        </div>
        <div id="pageShadow">
            <div id="pageInner" class="clearFix">
                <div id="sidebar" class="column">
                        <?php echo $this->RenderSidebar();?>
                </div>
                <div id="centerPane">
                    <div id="toolbar">
                       <?php
                           echo $this->RenderLinks($this->toolbarLinks, 'rightLinks');
                           echo $this->RenderLinks($this->breadcrumbs, 'breadcrumbs', $this->GetTranslation('You are here') . ': ', null, ' > ');
                       ?>
                    </div>
                    <div id="main">
                        <h2 class="top"><?php echo $this->placeholder('formHeadline');?></h2>
                        <div id="form">
                            <?php echo $this->RenderAlert();?>
                            <?php echo $this->layout()->form ?>
                        </div>
                    </div>
                    <div id="options" class="column">
                        <?php echo $this->RenderOptions();?>
                    </div>
                </div>
            </div>
        </div>
        <div id="footer"></div>
    </div>
    <script type="text/javascript">
    $(document).ready(function() {
        <?php echo $this->placeholder('jquery');echo $this->placeholder('baseJquery');?>
    });
    </script>
</body>
</html>