<?php $this->placeholder('optionsHeadline')->set($this->GetTranslation('Module Browser'))?>

<p>
    We are currently working on a module browser.
    This browser will enable you to search a catalog of modules.
    These modules will include both community supported and commercial modules.
</p>
<p>
    The browser will enable you to download and install modules directly through the CMS,
    with no programming required.
</p>
<p>
    If you want to learn more about this and other upcoming features sign up for the Digitalus newsletter.
</p>
<p><?php echo $this->link($this->GetTranslation('Sign up for newsletter'), 'http://digitaluscms.com/newsletter', 'newspaper_add.png')?></p>
<p class='notice'>This is coming soon!</p>