<?php $this->placeholder('formHeadline')->set($this->getTranslation('Slideshow Module'));?>
<fieldset>
    <legend><?php echo $this->getTranslation('About')?></legend>
    <p><?php echo $this->getTranslation('The slideshow module enables you to publish slideshows on your site.');?></p>
    <p><?php echo $this->getTranslation('These slideshows consist of slides which each contain a picture, a title, and description. You can sort these slides to display in any order.');?></p></p>
</fieldset>

<fieldset>
    <legend><?php echo $this->getTranslation('Create a new slideshow');?></p></legend>
    <?php echo $this->form; ?>
</fieldset>
