<div class="newsCenter">
<h2>Current News</h2>

<?php if(count($this->items) > 0){?>
    <ul>
        <?php
        foreach ($this->items as $item){
        ?>
        <li><span class="date"><?php echo date('m.d.y',$item->publish_date);?></span> | <a href="<?php echo $this->CleanUri(true);?>/p/openItem/<?php echo $item->id;?>"><?php echo $item->title;?></a></li>
        <?php } ?>
    </ul>
<?php }else{ ?>
<p>There are no articles currently</p>
<?php } ?>

</div>
