<?php 
//render the search form
//echo $this->render('./assets/searchform.phtml');
if($this->centers){
?>
<h2>News Centers</h2>
<?php
    foreach ($this->centers as $center){
?>
<h3><a href="<?php echo $this->CleanUri(true);?>/p/openCenter/<?php echo $center->id;?>"><?php echo $center->title;?></a></h3>
<p><?php echo $this->TruncateText($center->content, 50);?></p>
<?php
    }
}else{ ?>
<p>There are no news centers to view</p>
<?php } ?>

