<p><?php echo $this->GetTranslation("Current Version:")?> <strong>

<?php 
$config = Zend_Registry::get('config');
$siteVersions = $config->language->translations;
$version = $this->version;
echo $siteVersions->$version;
?>
</strong></p>

<?php if($siteVersions) { ?>
<p><?php echo $this->GetTranslation("Available Versions")?>: </p>
<ul>
<?php 
$pageMdl = new Page();
$pageVersions = $pageMdl->getVersions($this->pageId);
$defaultVersion = $pageMdl->getDefaultVersion();

foreach ($siteVersions as $key => $version) {
    if(isset($pageVersions[$key])) {
        $icon = "flag_green.png";
    }else{
        $icon = "flag_red.png";
    }
    if($key == $defaultVersion) {
        $version .= " (default)";
    }
    echo "<li>" . $this->link($version, "/admin/page/edit/id/" . $this->pageId . "/version/" . $key, $icon) . "</li>";
}
?>
</ul>
<?php } ?>