<div class="formBox">
	<h2>Admin access log</h2>
	<table class='spreadsheet' cellpadding="0" cellspacing="0">
		<tr>	
			<th>Date</th>
			<th>First Name</th>	
			<th>Last Name</th>	
			<th>Role</th>	
			<th>IP</th>	
			<th>Page</th>	
		</tr>
	<?php foreach ($this->accessLog as $entry){ ?>
		<tr>
			<td><?php echo $entry->date;?>&nbsp;</td>
			<td><?php echo $entry->first_name;?>&nbsp;</td>
			<td><?php echo $entry->last_name;?>&nbsp;</td>
			<td><?php echo $entry->role;?>&nbsp;</td>
			<td><?php echo $entry->ip;?>&nbsp;</td>
			<td><?php echo $entry->page;?>&nbsp;</td>
		</tr>
	<?php } ?>
	</table>
	
</div>
