<div class="formBox">
<h2 class="settings">Currently Editing</h2>
<p><b>Event:</b> <?php echo $this->data->title;?></p>
<p><b>Date / Time:</b> <?php echo $this->RenderEventDate($this->data);?></p>
<p><a href="/mod_event">Back to events home page...</a></p>
</div>

<div class="formBox">
<h2 class="trash">Delete Event</h2>
<p>Would you like to permanently this event?</p>
<p><a href="/mod_event/index/delete/id/<?php echo $this->data->id;?>" class='deleteConfirm' title='event'>Delete event</a></p>
</div>