<?php ?>
<h2><?php echo $this->translate('Update Successfull!');?></h2>
<p><?php echo $this->translate('Digitalus CMS was successfully updated on your domain.');?></p>
<p><?php echo $this->translate('Before you use it you must completely delete the <strong>install</strong> folder, as in this screenshot:');?></p><br /><br />
<img src="./images/assets/screenshots/delete-install-folder.png" alt="screenshot" /><br /><br />
<p><?php echo $this->translate('Once that folder is deleted Digitalus will automatically load when you visit this domain.');?></p>
