<?php
$this->placeholder('formHeadline')->set($this->getTranslation('Update Page'));
$this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/markitup/jquery.markitup.js');
$this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/markitup/sets/default/set.js');
$this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/markitup/sets/textile/set.js');
$this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/markitup/sets/html/set.js');

$this->headLink()->appendStylesheet($this->getBaseUrl() . '/scripts/markitup/skins/markitup/style.css');
$this->headLink()->appendStylesheet($this->getBaseUrl() . '/scripts/markitup/sets/textile/style.css');
$this->headLink()->appendStylesheet($this->getBaseUrl() . '/scripts/markitup/sets/html/style.css');
//jquery block
$this->jQuery()->onLoadCaptureStart()?>
$(".wiki").markItUp(myWikiSettings);
$(".html").markItUp(myHtmlSettings);
<?php $this->jQuery()->onLoadCaptureEnd()?>

<div id="content">
<fieldset>
    <legend><?php echo $this->getTranslation('Edit Content');?></legend>
    <?php echo $this->render('page/edit/content.phtml');?>
</fieldset>

</div>

<fieldset id="meta">
    <legend><?php echo $this->getTranslation('Edit Meta Data');?></legend>
    <?php echo $this->render('page/edit/meta.phtml');?>
</fieldset>

<fieldset id="properties">
    <legend><?php echo $this->getTranslation('Edit Page Properties');?></legend>
    <?php echo $this->render('page/edit/properties.phtml');?>
</fieldset>

<!--
this is not going to make it in the beta version
<fieldset id="relatedContent">
    <legend><?php echo $this->getTranslation('Related Content');?></legend>
    <?php echo $this->render('page/edit/relatedContent.phtml');?>
</fieldset>

<fieldset id="attachments">
    <legend><?php echo $this->getTranslation('Attachments');?></legend>
    <?php echo $this->render('page/edit/attachments.phtml');?>
</fieldset>
 -->

<fieldset id="template">
    <legend><?php echo $this->getTranslation('Content Template');?></legend>
    <?php echo $this->render('page/edit/template.phtml');?>
</fieldset>

<fieldset id="design">
    <legend><?php echo $this->getTranslation('Page Design');?></legend>
    <?php echo $this->render('page/edit/design.phtml');?>
</fieldset>

<fieldset id="move">
    <legend><?php echo $this->getTranslation('Move Page');?></legend>
    <?php echo $this->render('page/edit/move.phtml');?>
</fieldset>
