<?php
$this->placeholder('formHeadline')->set($this->getTranslation('Create a Page'));
?>
<fieldset>
    <legend><?php echo $this->getTranslation('Create Page');?></legend>
    <form action="<?php echo $this->getBaseUrl();?>/admin/page/new" method="post">
    <p><?php echo $this->getTranslation('To create a new page...');?></p>
    <h3><?php echo $this->getTranslation('Step 1: Select the parent section');?></h3>
    <dl>
    <?php
    echo $this->FormRow(
        $this->getTranslation('Parent Page'),
        $this->SelectPage('parent_id',
        $this->createPageOptions->parentId) . $this->formButton('step1button', $this->getTranslation('Next >>'), array('class' => 'inlineButton'))
    );
    ?>
    </dl>
    <div id="step2"></div>
    <div id="step3"></div>
    </form>
</fieldset>
<?php $this->jQuery()->onLoadCaptureStart(); ?>
    $("#step1button").click(function() {
        var parentId = $("#parent_id").val();
        $("#step2").load('<?php echo $this->getBaseUrl();?>/admin/page/select-content-template/parent_id/' + parentId);
        $("#step3").html('');
        return false;
    });
<?php $this->jQuery()->onLoadCaptureEnd(); ?>
