<p><?php echo $this->getTranslation('page_my_pages_intro');?></p>

<?php
$content = new Model_Page();
$pages = $content->getCurrentUsersPages();
if ($pages) {
    ?>
    <ul>
    <?php foreach ($pages as $page) { ?>
        <li class="page"><a href="<?php echo $this->getBaseUrl();?>/admin/page/open/id/<?php echo $page->id;?>" title="<?php echo $this->RenderDate($page->create_date);?>"><?php echo $page->title;?></a></li>
    <?php } ?>
    </ul>
<?php } ?>
