<?php $this->placeholder('formHeadline')->set($this->getTranslation('Update Page'));

echo $this->render('page/edit/content.phtml');

if ($this->isAllowed('admin', 'page', 'update-meta-data')) {?>
<fieldset id="meta">
    <legend><?php echo $this->getTranslation('Edit Meta Data');?></legend>
    <?php echo $this->render('page/edit/meta.phtml');?>
</fieldset><?php
}
if ($this->isAllowed('admin', 'page', 'update-properties')) {?>
<fieldset id="properties">
    <legend><?php echo $this->getTranslation('Edit Page Properties');?></legend>
    <?php echo $this->render('page/edit/properties.phtml');?>
</fieldset><?php
}
if ($this->isAllowed('admin', 'page', 'update-template')) {?>
<fieldset id="template">
    <legend><?php echo $this->getTranslation('Content Template');?></legend>
    <?php echo $this->render('page/edit/template.phtml');?>
</fieldset><?php
}
if ($this->isAllowed('admin', 'page', 'move')) {?>
<fieldset id="move">
    <legend><?php echo $this->getTranslation('Move Page');?></legend>
    <?php echo $this->render('page/edit/move.phtml');?>
</fieldset><?php
}
if ($this->isAllowed('admin', 'page', 'publish')) {?>
<fieldset id="publish">
    <legend><?php echo $this->getTranslation('Publish / Archive Page');?></legend>
    <?php echo $this->render('page/edit/publish.phtml');?>
</fieldset><?php
}
