<?php $this->placeholder("optionsHeadline")->set($this->GetTranslation("Page Options"))?>

<ul class="idTabs">
	<li><?php echo $this->link('Content', '#content', 'page_white_edit.png');?></li>
	<li><?php echo $this->link('Page Head and Meta Data', '#meta', 'page_white_code.png');?></li>
	<li><?php echo $this->link('Properties', '#properties', 'textfield_add.png');?></li>
	<li><?php echo $this->link('Attachments', '#attachments', 'page_white_stack.png');?></li>
	<li><?php echo $this->link('Related Content', '#relatedContent', 'page_white_link.png');?></li>
	<li><?php echo $this->link('Make Home Page', '/admin/page/make-home-page/id/' . $this->pageId, 'house.png');?></li>
	<li><?php echo $this->link('Design', '#design', 'layout_content.png');?></li>
	<li><?php echo $this->link('Move Page', '#movePage', 'arrow_turn_right.png');?></li>
</ul>

<p class='notice'>The page attachments and related content are not implemented yet!</p>




