<?php 
//register the helpers (ajax request)
DSF_View_RegisterHelpers::register($this);

if(is_array($this->allowedTemplates)){?>
<h3><?php echo $this->GetTranslation("Step 2: What type of page would you like to create?")?></h3>
<?php 

        //load the common helpers
        DSF_View_RegisterHelpers::register($this);
echo $this->FormRow(
	$this->GetTranslation("Select a type", null, $this), 
	$this->formSelect('contentType', null, null, $this->allowedTemplates) . 
	$this->formButton("step2button",$this->GetTranslation("Next >>", null, $this), array('class' => 'inlineButton')));
}else{?>
<p><?php echo $this->GetTranslation("You can not add any pages to this section.", null, $this)?></p>
<?php } ?>

<script type="text/javascript">
$(document).ready(function() {
	$("#step2button").click(function(){
		$("#step3").load('/admin/page/create-page-form');
		return false;
	});  
});
</script>