 <?php $this->placeholder("sidebarHeadline")->set('Pages')?>

<div id='contentBrowser'>
<script type="text/javascript">
$(document).ready(function()
{
	$("#fileTree").treeview({			
		persist: "cookie",
		collapsed: true,
		unique: true
	});
}
);
</script>
<?php echo $this->RenderFileBrowser(0);?>
<p class='note'><?php echo $this->GetTranslation('Note: The filenames are displayed as: (menu label/page title)');?></p>
</div>