<?php $this->placeholder('sidebarHeadline')->set($this->getTranslation('Pages'));

$this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/jquery.treeview.min.js');
$this->jQuery()->addJavascriptFile($this->getBaseUrl() . '/scripts/jquery.cookie.js');
$this->jQuery()->onLoadCaptureStart();?>
    $("#fileTree").treeview({
        persist: "cookie",
        collapsed: true,
        unique: true
    });
<?php $this->jQuery()->onLoadCaptureEnd();?>
<div class='contentBrowser'>
<?php echo $this->RenderFileBrowser(0, '/admin/page/edit/id/');?>
</div>