<?php
// xml declaration and doc type
echo $this->getXmlDeclaration();
echo $this->doctype() . PHP_EOL;

// set site-wide meta data
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=' . $this->placeholder('charset'))
                 ->appendHttpEquiv('Content-Language', 'en-US');
?>
<html<?php echo $this->isXhtml();?>>
    <head>
<!--        <meta http-equiv="Content-Type" content="text/html; charset=<?php //echo $this->placeholder('charset');?>" />-->
        <?php
            echo $this->placeholder('google_verify');
            echo $this->headMeta();
            echo $this->headTitle();
            echo $this->headScript();
            echo $this->headLink();
            echo $this->headStyle();
        ?>
        <style type="text/css">
            <?php echo $this->placeholder('inlineStyles'); ?>
        </style>
    </head>
    <body>
        <?php
            echo $this->layout()->page;
            echo $this->placeholder('google_tracking');
        ?>
    </body>
</html>