<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Digitalus Site Manager <?php echo $this->escape($this->title); ?></title>
<?php 

    $styleSheets = array(
        'admin.css',
        'adminMenu.css',
        'adminForms.css',
        'datePicker.css',
        'filetree.css',
        'jquery.treeview.css',
		'ThickBox.css',
		'icons.css',
		'spreadsheet.css',
		'sortable.css'
    );
    echo $this->StyleSheets($styleSheets);
    
    $scripts = array(
        'jquery-1.2.1.pack.js',
        'interface.js',
        'jqueryTooltip.js',
        'jqueryDatePicker.js',
		'ThickBox.js',
		'jquery.treeview.js',
		'jquery.cookie.js'
    );
    echo $this->Scripts($scripts);

?>
	
<script>
$(document).ready(function() {
	$('#menu_<?php echo $this->adminSection;?>').addClass('selectedNav'); 

	$.datePicker.setDateFormat('myd', '-');
	$('input.date-picker').datePicker({startDate:'01/01/2007'});
	
    $('.showTip').Tooltip({showURL: false, showBody: " - "});

    $(".message_box").bind("click",function(){
           $(this).fadeOut("slow");
      });

  	  $('a.deleteConfirm').bind('click',function(){
	  	var t = $(this).attr('title');
	  	var answer = confirm('Are you sure you want to delete this ' + t + "?");
	    if(!answer){return false;}
	  });
	  
	  $('.spreadsheet tr:odd').addClass('oddRow');
	  
 });
</script>

</head>

<body>
<div id="pageWrapper">
    <div id="header">
		<div id='headerRight'>
			<?php echo $this->CurrentAdminUser();?>
		</div>
        <br class="clear"/>
        <?php echo $this->render('./adminmenu.phtml');?>
    </div>

	<div id="body" class="boxBelow">
		<div id="contentWrapper">
			<?php echo $this->RenderAlert();?>
			<?php if(!empty($this->fullPageForm)){ //using this you can set the whole page to be a form?>
				<form action='<?php echo $this->fullPageForm;?>' method='post'>
			<?php } ?>
				<div id="leftPane">
					<?php echo $this->RenderSidebar();?>
				</div>
				<div id="centerPane">
			    	<?php 
			        	echo $this->render($this->actionScript);
			    	?>
				</div>
			<?php if(!empty($this->fullPageForm)){ //using this you can set the whole page to be a form?>
				</form>
			<?php } ?>
			<br class="clear"/>
		</div>
	</div>
	<div id="footer">
	<?php if($this->currentUser->role == 'admin'){?>
	<p>|&nbsp;<a href="/site">Site Settings</a>&nbsp;|&nbsp;<a href="/user">Users</a>&nbsp;|</p>
	<?php } ?>
`	</div>
</div>
</body>
