<?php $this->placeholder('formHeadline')->set($this->getTranslation('Contact Form'));?>

<fieldset>
    <p><?php echo $this->getTranslation('You can set the following options on the contact form:');?></p>
    <dt><?php echo $this->getTranslation('Recipient') . ':</dt><dd>' . $this->getTranslation('who you want to receive the messages');?></dd>
    <dt><?php echo $this->getTranslation("Recipient's email") . ':</dt><dd>' . $this->getTranslation("the recipient's email address");?></dd>
</fieldset>