<div class="formBox">
<h2>Currently Editing</h2>
<p><b>Item:</b> <?php echo $this->Page->title;?></p>
</div>

<div class="formBox">
<h2 class="folder">View</h2>
<ul class="idTabs">
    <li><a href="/admin/page/open/id/<?php echo $this->Page->id;?>">Edit Content</a></li>
    <li><a href="#advancedOptions">About</a></li>
    <li><a href="#designOptions">Design Options</a></li>
    <li><a href="#menuOptions">Menu Options</a></li>
    <li><a href="#modules">Modules</a></li>
    <li><a href="#movePage">Move Page</a></li>
</ul>
</div>