<?php $this->placeholder("sidebarHeadline")->set($this->GetTranslation('Current Designs'))?>
<?php
if (is_object($this->designs)) {
    $links = array();
    foreach ($this->designs as $design) {
        $links[] = $this->link($design->name, '/admin/design/update/id/' . $design->id, 'layout_content.png');
    }
    echo $this->htmlList($links, null, null, false);
}
?>
<p><?php echo $this->link('Create a new design', '/admin/design', 'layout_add.png');?></p>
