<h2>Bookmark Page</h2>
<div id='bookmarkPage'>
<?php 
$url = $this->RealPath($this->page->id);
$base = $_SERVER['HTTP_HOST'];
$path = strtolower("http://" . $base . '/' . DSF_Toolbox_String::addHyphens($url));
?>
<a href="http://del.icio.us/post?url=<?php echo $path; ?>&title=<?php echo $this->pageObj->getHeadline(); ?>" target="_blank">
    <img src="/public/images/bookmark_icons/delicious.png" alt="Del.icio.us" /></a>
<a href="http://digg.com/submit?phase=2&url=<?php echo $path; ?>" target="_blank">
    <img src="/public/images/bookmark_icons/digg.png" alt="Digg" /></a>
<a href="http://technorati.com/cosmos/search.html?url=<?php echo $path; ?>" target="_blank">
    <img src="/public/images/bookmark_icons/technorati.png" alt="Technorati" /></a>
<a href="http://myweb2.search.yahoo.com/myresults/bookmarklet?u=<?php echo $path; ?>&title=<?php echo $this->pageObj->getHeadline(); ?>" target="_blank">
    <img src="/public/images/bookmark_icons/yahoo.png" alt="yahoo" /></a>
<a href="http://www.google.com/bookmarks/mark?op=add&title=<?php echo $this->pageObj->getHeadline(); ?>&labels=&annotation=<?php echo $this->pageObj->getHeadline(); ?>&bkmk=<?php echo $path; ?>" target="_blank"><img src="/public/images/bookmark_icons/google.png" alt="google" /></a>
</div>
