<form action="<?php echo $this->ModuleAction();?>" method="POST" class="searchForm">
<p>Enter the keywords you would like to search for: <?php echo $this->formText('query') . $this->formSubmit('search','Search Site');?></p>
</form>
<div id="searchResults">
<?php if($this->searchResults){ ?>
<p>Your search for <em><?php echo $this->queryString;?> </em> returned <?php echo count($this->searchResults);?> <?php echo $this->Pluralize('result', count($this->searchResults))?></p>

<?php foreach ($this->searchResults as $result) { ?>
<h3><a href="/<?php echo DSF_Toolbox_String::addHyphens($this->RealPath($result->content_id));?>"><?php echo $result->content_title;?></a></h3>
<p>
    <?php 
        echo $this->TruncateText($result->content, 50);
    ?>
</p>
<?php };}  ?>

</div>