<?php $this->placeholder('optionsHeadline')->set($this->getTranslation('Need Help?'));?>
<p class="padding-10"><?php echo $this->getTranslation('If you are having trouble logging in please enter your email address below and we will send you your login credentials.');?></p>
<form class="padding-10" action="/admin/auth/reset-password" method="post">
<?php
    echo $this->FormText('email', $this->email);
    echo $this->FormSubmit('reminder', $this->getTranslation('Reset Password'));
?>
</form>
