<?php $this->placeholder('optionsHeadline')->set($this->getTranslation('Download'))?>

<p class="padding-10">
    We are currently working on a module browser.
    This browser will enable you to search a catalog of modules.
    These modules will include both community supported and commercial modules.
</p>
<p class="padding-10">
    The browser will enable you to download and install modules directly through the CMS,
    with no programming required.
</p>
