<?php 
echo $this->FormRow('Select the module page', 
    $this->SelectModulePage('moduleAction', $this->moduleName, null, array('id' => 'modulePage')));
?>
<script>
$(document).ready(function() {
	$('#modulePage').change(function(){
	    var action = $(this).val();
	    $('#moduleFormWrapper').load('/admin/module/render-form/modulename/<?php echo $this->moduleName;?>/moduleaction/' + action);
	});
 
 });
</script>