<fieldset>
    <label>Contact Form Options</label>
    <?php
    echo $this->FormRow('Enter the recipient:', $this->formText('param[recipient]', $this->formParams['recipient']));
    echo $this->FormRow('Enter the recipients email:', $this->formText('param[email]', $this->formParams['email']));
    echo $this->FormRow('Autoresponse subject (optional):', $this->formText('param[autoresponse_subject]', $this->formParams['autoresponse_subject'], array('class' => 'med')));
    echo $this->FormRow('Autoresponse message(optional):', $this->formTextarea('param[autoresponse_message]', $this->formParams['autoresponse_message'], array('class' => 'med')));
    echo $this->FormRow('Success message:', $this->formText('param[successMessage]', $this->formParams['successMessage'], array('class' => 'med')));
    echo $this->FormRow('Error message:', $this->formText('param[errorMessage]', $this->formParams['errorMessage'], array('class' => 'med')));
    ?>
</fieldset>