<p>The events calendar module opens an events calendar.  It displays the introduction content for the calendar, then the upcoming events
that are associated with it.</p>

<fieldset>
    <label>Select a calendar to display</label>
    <?php
    $select = $this->SelectCalendar('param[calendar]', $this->formParams['calendar']);
    if(!empty($select)){
    echo $this->FormRow('Select the calendar:', $select);
    }else{
        echo "<p>There are no calendars to view";
    }
    ?>
</fieldset>