<?php 
$this->placeholder('header_logo_content')->set(
    "<a href='http://digitaluscms.com'><img src='/images/logo.png' alt='Powered by Digitalus CMS' /></a>"
);

$this->placeholder('header_search_content')->set(
    $this->partial('partials/header/search-form.phtml')
);

$this->placeholder('content_content')->set(
    $this->RenderContentTemplate($this->page->getContentTemplate(), $this->page->getContent())
);

$this->placeholder('nav_content')->set("nav");
$this->placeholder('sidebar_content')->set("sidebar");

$this->placeholder('footer_content')->set(
    $this->partial('partials/footer.phtml')
);

$grid = $this->Grid960(16);

$header = $grid->addUnit('header', 16);
    $logo = $grid->startRow('header_logo', 10, $header);
    $search = $grid->endRow('header_search',6,$header);

$nav = $grid->addUnit('nav', 16);

$body = $grid->addUnit('body', 16);
    $content = $grid->startRow('content', 12, $body);
    $sidebar = $grid->endRow('sidebar', 4, $body);

$footer = $grid->addUnit('footer', 16, $body);
echo $grid->render();
?>
