<div id="pageWrapper">
	<div id="header"><h2>My CMS Project</h2></div>
	<div id="nav">
		<?php echo $this->placeholder('nav') ?>&nbsp;
	</div>
	<div id="sidebar">
		<div id="subNav">
			<?php echo $this->placeholder('subNav') ?>&nbsp;
		</div>
		<div id="adminMenu">
			<?php echo $this->placeholder('adminMenu') ?>&nbsp;
		</div>
		<div id="userForm">
			<?php echo $this->placeholder('userForm') ?>&nbsp;
		</div>
	</div>
	<div id="main">
		<h1><?php echo $this->placeholder('headline') ?></h1>
		<?php echo $this->layout()->content ?>
	</div>
	<div id="footer">
		<?php echo $this->placeholder('footer') ?>&nbsp;
	</div>
</div>
