<?php $this->placeholder("formHeadline")->set('Design')?>
<p>Info about design...</p>

<h3>Create a new design</h3>
<form action="<?echo $this->baseUrl;?>/admin/design/create" method="post">
<fieldset>
    <legend><?php echo $this->GetTranslation('Design details');?></legend>
    <?php 
    	echo $this->FormRow(
    		$this->GetTranslation('Design Name'), $this->FormText('name')
   		);
		echo $this->FormRow(
			$this->GetTranslation('Design Notes'), $this->FormTextarea('notes', null, array('class' => 'med'))
		);
	echo $this->FormRow(
		'&nbsp;', $this->FormSubmit('site',$this->GetTranslation('Update Design')));
    ?>
</fieldset>
