<?php $this->placeholder("sidebarHeadline")->set('Design')?>
<p>The design section is where you build your page designs.</p>

<h3>Current Designs</h3>
<?php 
if(is_object($this->designs)) {
	$links = array();
	foreach ($this->designs as $design) {
		$links[] = $this->link($design->name, $this->baseUrl . '/admin/design/update/id/' . $design->id, 'layout_content.png');
	}
	echo $this->htmlList($links, null, null, false);
}
?>
<p><?php echo $this->link('Create a new design', '/admin/design', 'layout_add.png');?></p>

