<?php 
    $baseUrl = $this->getBaseUrl();
    if(!empty($baseUrl)){ $siteRoot = $baseUrl . '/'; } else { $siteRoot = '/'; }
    $basePath = $siteRoot . $this->mediaFolder;
    if(!empty($this->filepath)) {
        $basePath .= '/' . $this->filepath;
    }
?>
<?php if (is_array($this->folders) && count($this->folders) > 0) { ?>
<h3><?php echo $this->getTranslation('Subfolders');?></h3>
<?php
    foreach ($this->folders as $folder) {
        $cleanPath = Digitalus_Toolbox_String::stripHyphens($folder);
        $cleanPath = Digitalus_Toolbox_String::stripUnderscores($folder);
?>
<div class='folderWrapper'>
    <?php
        $deleteLink = '/admin/media/delete-folder/folder/' . $this->mediapath . '_' . $folder;
        echo $this->link('Delete', $deleteLink, 'delete.png', 'rightLink delete');
    ?>
    <h4>
        <?php
            $path = '/admin/media/open-folder/folder/' . $this->mediapath . '_' . $folder;
            echo $this->link($folder, $path, 'folder.png');
        ?>
    </h4>
    <p>
        <?php 
            echo $this->getTranslation('Full path') . ': <code>' . $basePath . '/' . $cleanPath . '</code>';
        ?>
    </p>
</div>
<?php
    }
}

if (is_array($this->files) && count($this->files) > 0) { ?>
<h3><?php echo $this->getTranslation('Files');?></h3>
<?php
    foreach ($this->files as $file) {
        if (substr($file,0,1) != '.') {
            $filePath = Digitalus_Toolbox_String::stripUnderscores($this->basePath) . '/' . $file;
?>

<div class='fileWrapper'>
    <?php
        $fileLink = $this->mediapath . '_' . $file;
        $deleteLink = '/admin/media/delete-file/file/' . $fileLink . '/';
        echo $this->link('Delete', $deleteLink, 'delete.png', 'rightLink delete');
    ?>
    <h4>
        <?php
            $path = $this->mediaFolder . '/' . $this->filepath . $filePath;
            echo $this->link($file, $path, $this->getIconByFiletype($filePath, false));
        ?>
    </h4>
    <p><?php echo $this->getTranslation('Full path') . ': <code>' . $basePath . $filePath . '</code>';?></p>
</div><?php
        }
    }
}

?>