<div class="formBox">
	<h2>Admin access log</h2>
	<table class='spreadsheet' cellpadding="0" cellspacing="0">
		<tr>	
			<th><?php echo $this->GetTranslation('Date');?></th>
			<th><?php echo $this->GetTranslation('Name');?></th>
			<th><?php echo $this->GetTranslation('Page');?></th>	
		</tr>
	<?php foreach ($this->accessLog as $entry){ ?>
		<tr>
			<td><?php echo $entry->date;?>&nbsp;</td>
			<td><?php echo $entry->first_name . ' ' . $entry->last_name;?>&nbsp;</td>
			<td><?php echo $entry->page;?>&nbsp;</td>
		</tr>
	<?php } ?>
	</table>
	
</div>
