<form action="<?php echo $this->getBaseUrl();?>/admin/user/create" method="post">
    <fieldset>
        <legend>General Information</legend>
        <?php
        $data = new Digitalus_Data_Storage();
        $user = $data->get();
        $tmpUser = new stdClass();
        if ($user) {
            $tmpUser = $user;
        } else {
            $tmpUser->first_name = null;
            $tmpUser->last_name = null;
            $tmpUser->email = null;
            $tmpUser->role = null;
        }

            echo $this->FormRow($this->getTranslation('First Name'), $this->FormText('first_name', $tmpUser->first_name));
            echo $this->FormRow($this->getTranslation('Last Name'), $this->FormText('last_name', $tmpUser->last_name));
            echo $this->FormRow($this->getTranslation('Email Address'), $this->FormText('email', $tmpUser->email));
            echo $this->FormRow($this->getTranslation('Admin Role'), $this->SelectAdminRole('role', $tmpUser->role));
            echo $this->FormRow($this->getTranslation('Password'), $this->FormPassword('newPassword'));
            echo $this->FormRow($this->getTranslation('Confirm Password'), $this->FormPassword('newConfirmPassword'));
            echo $this->FormRow('&nbsp;', $this->FormSubmit('update_password', $this->getTranslation('Create User')));
        ?>
    </fieldset>
</form>
