<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>
    <?php echo $this->GetTranslation('Digitalus CMS') . $this->escape($this->title); ?></title>
<?php 
//style sheets
$this->headLink()->appendStylesheet('/skins/digitalus-1-5/styles/layout.css')
                 ->appendStylesheet('/skins/digitalus-1-5/styles/text.css') 
                 ->appendStylesheet('/skins/digitalus-1-5/styles/nav.css')
                 ->appendStylesheet('/skins/digitalus-1-5/styles/style.css')
                 ->appendStylesheet('/skins/digitalus-1-5/styles/form.css')
                 ->appendStylesheet('/styles/datePicker.css') 
                 ->appendStylesheet('/styles/adminForms.css') 
                 ->appendStylesheet('/styles/filetree.css') 
                 ->appendStylesheet('/styles/menutree.css') 
                 ->appendStylesheet('/styles/jquery.treeview.css') 
                 ->appendStylesheet('/styles/spreadsheet.css')
                 ->appendStylesheet('/styles/jquery.wysiwyg.css') 
                 ->appendStylesheet('/styles/sortable.css'); 
echo $this->headLink();

//javascripts
$this->headScript()->prependFile('/scripts/jquery.pack.js')
                   ->appendFile('/scripts/interface.js')
                   ->appendFile('/scripts/jqueryTooltip.js')
                   ->appendFile('/scripts/jqueryDatePicker.js')
                   ->appendFile('/scripts/jquery.dateCompletion.js')
                   ->appendFile('/scripts/jquery.treeview.js')
                   ->appendFile('/scripts/idTabs.js')
                   ->appendFile('/scripts/jquery.wysiwyg.js')
                   ->appendFile('/scripts/jquery.cookie.js');
echo $this->headScript();

//jquery block
$this->placeholder('jquery')->captureStart();
?>
$(".message_box").bind("click",function(){
       $(this).fadeOut("slow");
  });

	  $('a.delete').bind('click',function(){
  	var answer = confirm('Are you sure you want to delete this?');
    if(!answer){return false;}
  });
  
$('a.add_to_bookmarks').click(function(){
    var label = prompt('Bookmark label:');
    if(label){
	    var url = $(this).attr('href');
	    url += '/label/' + label;
	    if(jQuery.get(url)){
	        alert('Your bookmark was successfully saved.');
	    }
    }
    return false;
});

$('.wysiwyg').wysiwyg();
  
$('.spreadsheet tr:odd').addClass('oddRow');
  
<?php $this->placeholder('jquery')->captureEnd();?>	
</head>

<body>
	<div id="page">
    	<div id="header">
        	<?php 
        	   echo $this->CurrentAdminUser();
        	   echo $this->RenderAdminMenu();
    	   ?>
        </div>
        <div id="pageShadow">
        	<div id="pageInner" class="clearFix">
            	<div id="sidebar" class="column">
                    	<?php echo $this->RenderSidebar();?>
                </div>
                <div id="centerPane">
                	<div id="toolbar">
                	   <?php 
                	       echo $this->RenderLinks($this->toolbarLinks, 'rightLinks');
                	       echo $this->RenderLinks($this->breadcrumbs, 'breadcrumbs', $this->GetTranslation('You are here') . ": ", null, ' > ');                	       
            	       ?>
                    </div>
                    <div id="main">
                        <h2 class="top"><?php echo $this->placeholder('formHeadline');?></h2>	
                        <div id="form">
                            <?php echo $this->RenderAlert();?>
                            <?php echo $this->layout()->form ?>
                        </div>
                    </div>
                    <div id="options" class="column">
                        <?php echo $this->RenderOptions();?>
                    </div>
                </div>
            </div>
        </div>
        <div id="footer"></div>
    </div>
</body>
<script type="text/javascript">
$(document).ready(function() {
	  <?php echo $this->placeholder('jquery');?>
});
</script>
</html>

