<?php 
$this->placeholder("formHeadline")->set($this->GetTranslation("Update Page"));

$this->headScript()->appendFile('/markitup/jquery.markitup.js');
$this->headScript()->appendFile('/markitup/sets/default/set.js');
$this->headScript()->appendFile('/markitup/sets/textile/set.js');

$this->headLink()->appendStylesheet('/markitup/skins/markitup/style.css');
$this->headLink()->appendStylesheet('/markitup/sets/textile/style.css');
//jquery block
$this->placeholder('jquery')->captureStart();
?>
$(".html").markItUp(mySettings);
$(".wiki").markItUp(myWikiSettings);
<?php $this->placeholder('jquery')->captureEnd();?>	                 

<div id="content">
<fieldset>
<legend><?php echo $this->GetTranslation("Edit Content");?></legend>
<?php echo $this->render('page/edit/content.phtml');?>
</fieldset>

<fieldset>
<legend><?php echo $this->GetTranslation("Page Version");?></legend>
<?php echo $this->render('page/edit/version.phtml');?>
</fieldset>
</div>

<fieldset id="meta">
	<legend><?php echo $this->GetTranslation("Edit Meta Data");?></legend>
	<?php echo $this->render('page/edit/meta.phtml');?>
</fieldset>

<fieldset id="properties">
	<legend><?php echo $this->GetTranslation("Edit Page Properties");?></legend>
	<?php echo $this->render('page/edit/properties.phtml');?>
</fieldset>

<fieldset id="relatedContent">
	<legend><?php echo $this->GetTranslation("Related Content");?></legend>
	<?php echo $this->render('page/edit/relatedContent.phtml');?>
</fieldset>

<fieldset id="attachments">
	<legend><?php echo $this->GetTranslation("Attachments");?></legend>
	<?php echo $this->render('page/edit/attachments.phtml');?>
</fieldset>

<fieldset id="design">
	<legend><?php echo $this->GetTranslation("Page Design");?></legend>
	<?php echo $this->render('page/edit/design.phtml');?>
</fieldset>

<fieldset id="move">
	<legend><?php echo $this->GetTranslation("Move Page");?></legend>
	<?php echo $this->render('page/edit/move.phtml');?>
</fieldset>
