<?php 
$grid = new DSF_Interface_Grid('page', 16);
$header = $grid->addElement('header', 16);
    $logo = $header->addElement('header_logo', 10);
    $logo->setAttribute('first', true);
    $top = $header->addElement('header_top',6);
    $top->setAttribute('last', true);
$header->setAttribute('clear', true);
    
$nav = $grid->addElement('nav', 16);
$nav->setAttribute('clear', true);

$body = $grid->addElement('body', 16);
	$sidebarLeft = $body->addElement('sidebar_left', 4);
    $sidebarLeft->setAttribute('first', true);
    $content = $body->addElement('content', 12);
    $content->setAttribute('last', true);
    
    $language = $content->addElement('language', 12);
    $language->setAttribute('first', true);
	$language->setAttribute('clear', true);
$body->setAttribute('clear', true);

$footer = $grid->addElement('footer', 16);
$footer->setAttribute('clear', true);

$this->placeholder('header_logo_content')->set(
    "<a href='http://digitaluscms.com'><img src='" . $this->baseUrl . "/images/logo.png' alt='Powered by Digitalus CMS' /></a>"
);

$this->placeholder('header_top_content')->set(
    ''
);

if(is_object($this->page) && $this->isError != true) {
    $this->content = $this->RenderContentTemplate($this->page->getContentTemplate(), $this->page->getContent());
    $this->submenu = $this->RenderSubmenu();
}

$this->placeholder('content_content')->set($this->content);

$this->placeholder('nav_content')->set(
    $this->RenderMenu(0)
);

$this->placeholder('sidebar_left_content')->set(
    $this->submenu
);

$this->placeholder('language_content')->set('language' . $this->ListLanguageLinks());

$this->placeholder('footer_content')->set(
    $this->partial('partials/footer.phtml')
);

echo $grid->render();
