<?php 
$this->placeholder('header_logo_content')->set(
    "<a href='/'><img src='/skins/digitalus_media/images/logo.jpg' alt='Digitalus Media' /></a>"
);
$this->placeholder('header_tagline_content')->set("<p>Intelligent Web Solutions</p>");

if(is_object($this->page)) {
    $this->content = $this->RenderContentTemplate($this->page->getContentTemplate(), $this->page->getContent());
    $this->submenu = $this->RenderMenu($this->page->getId(), 2);
}

$this->placeholder('content_content')->set($this->content);

$this->placeholder('nav_content')->set(
    $this->RenderMenu(0)
);

$this->placeholder('sidebar_content')->set(
    $this->submenu
);

$this->placeholder('footer_left_content')->set($this->renderNode('content-blocks/footer-left','content'));
$this->placeholder('footer_center_content')->set($this->renderNode('content-blocks/footer-center','content'));
$this->placeholder('footer_right_content')->set($this->renderNode('content-blocks/footer-right','content'));

$grid = $this->Grid960(16);

$header = $grid->addUnit('header', 16);
    $logo = $grid->startRow('header_logo', 6, $header);
    $search = $grid->endRow('header_tagline',6,$header);

$body = $grid->addUnit('body', 16);
    $content = $grid->startRow('content', 12, $body);
    $sidebar = $grid->endRow('sidebar', 4, $body);

$footer = $grid->addUnit('footer', 16);
    $footerLeft = $grid->startRow('footer_left', 4, $footer);
    $footerCenter = $grid->addUnit('footer_center', 8, $footer);
    $footerRight = $grid->endRow('footer_right',4,$footer);

echo $grid->render();
?>

