<?php 
$this->placeholder('header_logo_content')->set(
    "<a href='http://digitaluscms.com'><img src='/images/logo.png' alt='Powered by Digitalus CMS' /></a>"
);

$this->placeholder('header_search_content')->set(
    $this->partial('partials/header/search-form.phtml')
);

if(is_object($this->page)) {
    $this->content = $this->RenderContentTemplate($this->page->getContentTemplate(), $this->page->getContent());
    $this->submenu = $this->RenderMenu($this->page->getId(), 2);
}

$this->placeholder('content_content')->set($this->content);

$this->placeholder('nav_content')->set(
    $this->RenderMenu(0)
);

$this->placeholder('sidebar_content')->set(
    $this->submenu
);

$this->placeholder('footer_content')->set(
    $this->partial('partials/footer.phtml')
);

$grid = $this->Grid960(16);

$header = $grid->addUnit('header', 16);
    $logo = $grid->startRow('header_logo', 10, $header);
    $search = $grid->endRow('header_search',6,$header);

$nav = $grid->addUnit('nav', 16);

$body = $grid->addUnit('body', 16);
    $content = $grid->startRow('content', 12, $body);
    $sidebar = $grid->endRow('sidebar', 4, $body);

$footer = $grid->addUnit('footer', 16, $body);
echo $grid->render();
?>
