<?php $this->placeholder("optionsHeadline")->set($this->GetTranslation("Options"))?>
<ul class="idTabs">
    <li><a href="#browse"><?php echo $this->GetTranslation('Browse Folder');?></a></li>
    <li><a href="#upload"><?php echo $this->GetTranslation('Upload Media');?></a></li>
    <li><a href="#subfolder"><?php echo $this->GetTranslation('Create Subfolder');?></a></li>
    <li><a href="#rename"><?php echo $this->GetTranslation('Rename Folder');?></a></li>
</ul>

