 <?php $this->placeholder("sidebarHeadline")->set('Media')?>
<script type="text/javascript">
$(document).ready(function()
{
	$("#fileTree").treeview({			
		persist: "cookie",
		collapsed: true,
		unique: true
	});
}
);
</script>

<div class='contentBrowser'>

<?php echo $this->RenderMediaBrowser($this->pathToMedia,'admin/media/open-folder/folder',null);?>
</div>

<p class='notice'>Note that the media section has several outstanding tasks before it is complete.</p>