<div class="formBox">
<h2 class="note">Contact Form</h2>
<p>The contact form does not have any fixed settings.  You set it up page by page.</p>
</div>	

<div class="formBox">
<h2 class="note">Ask a Question</h2>
<p>The ask a question module allows you site users to ask you a question without going to the main contact form.</p>
<p><a href="/mod_contact/index/ask-question">Ask a question settings</a></p>
</div>	


