<div class="formBox">
<h2 class="contact">Contact Form</h2>
<img class="right" src="/public/images/assets/screenshots/module-form.png" />
<p>The contact form module enables you to add contact forms to your site's pages.</p>
<p>1. Go to the page you would like to add the form and click advanced options</p>
<p>2. In the select module page box select the contact module from the dropdown box</p>
<p>3. A new box will appear.  Select the module page from this list (we will use the contactform in this example)</p>
<p>4. A form will load with all of the options for the contact form.</p>
<h3>Contact form options</h3>
<p>You can set the following options on the contact form:</p>
<ul>
<li><b>Recipient</b> -> who you want to recieve the messages</li>
<li><b>Recipient's email</b> -> the recipient's email address</li>
<li><b>Autoresponse (optional)</b>
    <ul>
        <li><b>Subject</b> -> the subject of the autoresponse message</li>
        <li><b>Message</b> -> the message you want to send as the autoresponse body.  note that if this is not set the system will not send autoresponses</li>
    </ul>
</li>
<li><b>Success message</b> -> this message will be displayed after a message was sent successfully</li>
<li><b>Error message</b> -> this message will be displayed if there is an error sending the message</li>
</ul>

</div>	
