<?php
// first load the template
$this->loadTemplate('admin', 'default');

$this->placeholder('charset')->set('utf-8');
echo '<?xml version="1.0" encoding="' . $this->placeholder('charset') . '" ?>' . PHP_EOL;
echo $this->doctype() . PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>
    <?php echo $this->getTranslation('Digitalus CMS') . $this->escape($this->title); ?>
</title>
<?php
echo $this->layout()->pageHead;

// the loadTemplate() helper loads all of the stylesheets now

echo $this->headLink();
 
$this->jQuery()->onLoadCaptureStart();
?>
$(".message_box").bind("click",function(){
       $(this).fadeOut("slow");
  });

      $('a.delete').bind('click',function(){
    var answer = confirm('Are you sure you want to delete this?');
    if(!answer){return false;}
  });

$('a.add_to_my_bookmarks').click(function(){
    var label = prompt('Bookmark label:');
    if(label){
        var url = $(this).attr('href');
        url += '/label/' + label;
        if(jQuery.get(url)){
            alert('Your bookmark was successfully saved.');
        }
    }
    return false;
});

$('.spreadsheet tr:odd').addClass('oddRow');

<?php 
    $this->jQuery()->onLoadCaptureEnd(); 
?>
</head>

<body>
    <?php 
        echo $this->layout()->template;
        echo $this->jQuery(); 
    ?>
</body>
</html>