<?php
$this->placeholder('charset')->set('utf-8');
echo '<?xml version="1.0" encoding="' . $this->placeholder('charset') . '" ?>' . PHP_EOL;
echo $this->doctype() . PHP_EOL;
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>
    <?php echo $this->getTranslation('Digitalus CMS') . $this->escape($this->title); ?></title>
<?php
//style sheets
$this->headLink()->appendStylesheet($this->getBaseUrl() . '/skins/digitalus-1-5/styles/layout.css')
                 ->appendStylesheet($this->getBaseUrl() . '/skins/digitalus-1-5/styles/text.css')
                 ->appendStylesheet($this->getBaseUrl() . '/skins/digitalus-1-5/styles/nav.css')
                 ->appendStylesheet($this->getBaseUrl() . '/skins/digitalus-1-5/styles/style.css')
                 ->appendStylesheet($this->getBaseUrl() . '/skins/digitalus-1-5/styles/form.css')
                 ->appendStylesheet($this->getBaseUrl() . '/styles/datePicker.css')
                 ->appendStylesheet($this->getBaseUrl() . '/styles/adminForms.css')
                 ->appendStylesheet($this->getBaseUrl() . '/styles/filetree.css')
                 ->appendStylesheet($this->getBaseUrl() . '/styles/menutree.css')
                 ->appendStylesheet($this->getBaseUrl() . '/styles/jquery.treeview.css')
                 ->appendStylesheet($this->getBaseUrl() . '/styles/spreadsheet.css')
                 ->appendStylesheet($this->getBaseUrl() . '/styles/sortable.css');
echo $this->headLink();

//$this->jQuery()->addJavascriptFile('/scripts/jquery.multifile.js');
$this->jQuery()->addJavascriptFile('/scripts/idTabs.js');
$this->jQuery()->onLoadCaptureStart();
?>
$(".message_box").bind("click",function(){
       $(this).fadeOut("slow");
  });

      $('a.delete').bind('click',function(){
    var answer = confirm('Are you sure you want to delete this?');
    if(!answer){return false;}
  });

$('a.add_to_my_bookmarks').click(function(){
    var label = prompt('Bookmark label:');
    if(label){
        var url = $(this).attr('href');
        url += '/label/' + label;
        if(jQuery.get(url)){
            alert('Your bookmark was successfully saved.');
        }
    }
    return false;
});

$('.spreadsheet tr:odd').addClass('oddRow');

<?php 
    $this->jQuery()->onLoadCaptureEnd();
    echo $this->jQuery();  
?>
</head>

<body>
    <div id="page">
        <div id="header">
            <?php
               echo $this->CurrentAdminUser();
               echo $this->RenderAdminMenu();
           ?>
        </div>
        <div id="pageShadow">
            <div id="pageInner" class="clearFix">
                <div id="sidebar" class="column">
                        <?php echo $this->RenderSidebar();?>
                </div>
                <div id="centerPane">
                    <div id="toolbar">
                       <?php
                           echo $this->RenderLinks($this->toolbarLinks, 'rightLinks');
                           echo $this->RenderLinks($this->breadcrumbs, 'breadcrumbs', $this->getTranslation('You are here') . ': ', null, ' > ');
                       ?>
                    </div>
                    <div id="main">
                        <h2 class="top"><?php echo $this->placeholder('formHeadline');?></h2>
                        <div id="form">
                            <?php echo $this->RenderAlert();?>
                            <?php echo $this->layout()->form ?>
                        </div>
                    </div>
                    <div id="options" class="column">
                        <?php echo $this->RenderOptions();?>
                    </div>
                </div>
            </div>
        </div>
        <div id="footer"></div>
    </div>
</body>
</html>