<div class="formBox">
<h2>testing</h2>

<?php

$prop = new Properties();
$properties = $prop->load(54);
$modules = $properties->addGroup('modules');
$gallery = $modules->addGroup('gallery');
$gallery->addItem('name', 'My Pictures');
$images = $gallery->addGroup('images');
$images->addItem('My fish', '/files/images/fish.jpg');
$images->addItem('Aarons fish', '/files/images/smallFish.jpg');
$prop->save();
Zend_Debug::dump($properties);
?>
</div>

