<dt>
    <?php 
    echo $this->formLabel(
        $this->element->getName(),
        $this->element->getLabel()
    );
    ?>
</dt>
<dd class="<?php echo $this->class;?>">

<?php 
$elementName = $this->element->getName();
$values = $this->element->getXml();

//load values as url parameters
if($values) {
 foreach ($values as $k => $v) {
     $params[$k] = $v;
     $params[] = $k;
     $params[] = $v;   
 }
 $paramsString = implode('/', $params) . '/';
}
echo $this->SelectModule($elementName . "[module]", $values->module, $this->element->getAttribs());
?>
</dd>
<div class="moduleFormWrapper" id="<?php echo $elementName;?>_wrapper">
<?php 
    if(isset($values->module)){
         $params['element'] = $elementName;
         $params['moduleKey'] = $values->module;
        echo $this->action('render-form','module','admin',$params);
    }
?>
</div>
<script>
$(document).ready(function() {
	$('#<?php echo $elementName?>-module').change(function(){
	    var module = $(this).val();
	    $('#<?php echo $elementName;?>_wrapper').load('/admin/module/render-form/<?php echo $paramsString;?>element/<?php echo $this->element->getName() ?>/moduleKey/' + module);
	});
 
 });
</script>


<?php 
echo $this->formErrors($this->element->getMessages());
?>



