<p>Your server is properly configured to host the Digitalus CMS efficiently and securely!</p>

<form action="index.php?step=2" method="post">
    <h2>Site Admin Account</h2>
    <p>Digitalus CMS uses your email address as the username for the CMS, because it is unique and easy to remember.  
    You can enter what ever you like for a password, but bear in mind that your site is only as secure as this password!</p>
    
    <div class="formRow">
    	<label>Email Address:</label>
    	<?php echo $this->formText('email', $this->data['email'])?>
    	<br class="clear" />
    </div>
    <div class="formRow">
    	<label>Password:</label>
    	<?php echo $this->formPassword('account_password')?>
    	<br class="clear" />
    </div>
    
    <h2>Database Connection Information</h2>
    <p>Now you need to set up the database connection.  If you are unsure about this contact
    your hosting provider.</p>
    
    <div class="formRow">
    	<label>Database Name:</label>
    	<?php echo $this->formText('db_name', $this->data['db_name'])?>
    	<br class="clear" />
    </div>
    <div class="formRow">
    	<label>Database Host:</label>
    	<?php echo $this->formText('db_host', $this->data['db_host'])?>
    	<br class="clear" />
    </div>
    <div class="formRow">
    	<label>Database Username:</label>
    	<?php echo $this->formText('db_username', $this->data['db_username'])?>
    	<br class="clear" />
    </div>
    <div class="formRow">
    	<label>Database Password:</label>
    	<?php echo $this->formText('db_password', $this->data['db_password'])?>
    	<br class="clear" />
    </div>
    
    <h2>Install CMS</h2>
    <p>Please double check all of the information on this page.  If 
    everything looks right then click <b>Install Now</b> to install Digitalus CMS</p>
    <p><?php echo $this->formSubmit('install', "Install Now")?></p>
</form>
	